[package]
name = "tropel-input-postman"
version = "0.6.0"
edition.workspace = true
license.workspace = true
description = "Postman collection (v2.0/v2.1) input adapter for tropel."
repository.workspace = true
rust-version.workspace = true

[dependencies]
tropel-sdk.workspace = true
tropel-collection.workspace = true
inventory.workspace = true
serde.workspace = true
serde_json.workspace = true
