//! Pure, data-in/data-out auth header builders.
//!
//! # Why this module exists
//!
//! [`crate::signers`] implements every scheme, and every one of them is behind
//! the `reqwest` feature — because those signers mutate a `reqwest::Request`.
//! `reqwest` cannot compile to `wasm32-unknown-unknown`, so `tropel-core-wasm`
//! turns the feature off, and a browser embedder therefore cannot reach ANY of
//! the signers. KnockPort's digest/hawk/SigV4/OAuth1 configs are creatable and
//! importable today, and every send using them REFUSES.
//!
//! The signing itself was never reqwest-coupled — only the plumbing was. The
//! digest builder read exactly two things off the request (`method` and the
//! request-target), and computed everything else from the challenge. So the
//! fix is to move the computation here, ungated, and leave `signers.rs` as a
//! thin adapter that reads those fields off `reqwest::Request` and calls in.
//!
//! # What this module must never become
//!
//! A second implementation. `signers.rs` calls these functions; it does not
//! keep a parallel copy. That is the whole point — a signing byte-difference
//! is a 403 that takes a day to find, which is why D4 puts signing in Rust in
//! the first place. Two Rust copies would be the same mistake one layer down.
//!
//! The `native_vs_wasm` differential harness already covers OAuth1-HMAC, SigV4
//! and Hawk end to end. Anything moved here inherits that coverage precisely
//! because the signers keep calling it.

use base64::Engine as _;
use hmac::digest::KeyInit;
use hmac::{Hmac, Mac};
use md5::Digest as _;
use percent_encoding::{utf8_percent_encode, AsciiSet, NON_ALPHANUMERIC};
use sha1::Sha1;
use sha2::{Sha256, Sha512, Sha512_256};

// ── Hashes ──────────────────────────────────────────────────────────────────
// Moved here from `signers.rs` rather than duplicated: they are shared by the
// digest builders below and by SigV4's canonical-request hashing, and two
// copies of a hash helper is exactly the drift this module exists to prevent.

/// Hex SHA-256.
pub fn hex_sha256(bytes: &[u8]) -> String {
    hex::encode(Sha256::digest(bytes))
}

/// Hex SHA-512/256.
///
/// A SEPARATE hash with a different IV — **not** the first 256 bits of
/// SHA-512. Truncating SHA-512 produces wrong HA1 values (RFC 7616 §3.9.2);
/// that was a real bug here once.
pub fn hex_sha512_256(bytes: &[u8]) -> String {
    hex::encode(Sha512_256::digest(bytes))
}

/// Hex MD5. Weak, and mandatory: RFC 7616 defaults to it when a server omits
/// `algorithm`, and plenty of servers still do.
pub fn hex_md5(bytes: &[u8]) -> String {
    hex::encode(md5::Md5::digest(bytes))
}

/// Hash with the digest algorithm named by a challenge.
///
/// The `-sess` variants change only how HA1 is DERIVED (nonce and cnonce are
/// folded in); the hash function itself stays the base algorithm, so they map
/// to the same arm here.
pub fn digest_with(input: &str, algorithm: &str) -> String {
    match algorithm {
        "SHA-256" | "SHA-256-SESS" => hex_sha256(input.as_bytes()),
        "SHA-512-256" | "SHA-512-256-SESS" => hex_sha512_256(input.as_bytes()),
        _ => hex_md5(input.as_bytes()),
    }
}

// ── HTTP Digest (RFC 7616) ──────────────────────────────────────────────────

/// One header to attach.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HeaderOut {
    pub name: String,
    pub value: String,
}

/// Everything needed to answer a digest challenge.
///
/// Digest is two-phase and the CALLER drives the 401 → retry, so only the
/// challenge-response half is built here. `nc` is the caller's per-host
/// counter; `cnonce` is generated by the caller (CSPRNG in production, a fixed
/// value in tests so vectors are pinnable).
#[derive(Debug, Clone)]
pub struct DigestBuildParams<'a> {
    pub username: &'a str,
    pub password: &'a str,
    /// Uppercase HTTP method.
    pub method: &'a str,
    /// The request-target: path + query. NOT the full URL — RFC 7616's `uri`
    /// is the origin-form target, and signing the absolute URL is a classic
    /// source of 401 loops against strict servers.
    pub uri: &'a str,
    pub realm: &'a str,
    pub nonce: &'a str,
    pub nc: u64,
    pub cnonce: &'a str,
    /// `qop` from the challenge, if it offered one.
    pub qop: Option<&'a str>,
    /// `algorithm` from the challenge. `None` means the server omitted it, in
    /// which case RFC 7616 says MD5 — and the field is NOT echoed back, since
    /// some strict servers reject an explicit `algorithm=MD5`.
    pub algorithm: Option<&'a str>,
    pub opaque: Option<&'a str>,
}

/// Compute the digest `response` value (HA1/HA2 → response).
pub fn digest_response_value(p: &DigestBuildParams<'_>, algorithm: &str) -> String {
    let base = base_algorithm(algorithm);
    let ha1_plain = digest_with(&format!("{}:{}:{}", p.username, p.realm, p.password), base);
    // RFC 7616 §3.4.4: `-sess` folds the nonce and cnonce into HA1.
    let ha1 = if algorithm.to_ascii_uppercase().ends_with("-SESS") {
        digest_with(&format!("{}:{}:{}", ha1_plain, p.nonce, p.cnonce), base)
    } else {
        ha1_plain
    };
    let ha2 = digest_with(&format!("{}:{}", p.method, p.uri), base);
    match p.qop {
        Some(qop) => digest_with(
            &format!(
                "{}:{}:{:08x}:{}:{}:{}",
                ha1, p.nonce, p.nc, p.cnonce, qop, ha2
            ),
            base,
        ),
        None => digest_with(&format!("{}:{}:{}", ha1, p.nonce, ha2), base),
    }
}

/// The base hash for an algorithm name, with `-sess` stripped.
fn base_algorithm(algorithm: &str) -> &'static str {
    let upper = algorithm.to_ascii_uppercase();
    if upper.starts_with("SHA-512-256") {
        "SHA-512-256"
    } else if upper.starts_with("SHA-256") {
        "SHA-256"
    } else {
        "MD5"
    }
}

/// Does this challenge's `qop` offer `auth`?
///
/// `qop` is a comma-separated LIST (`qop="auth,auth-int"`). Only `auth` is
/// supported; `auth-int` needs the entity body folded into HA2, which the
/// caller does not supply. A challenge offering only `auth-int` therefore
/// falls back to the older no-qop form rather than claiming a qop it did not
/// compute — sending `qop=auth` with an `auth-int` response is an
/// authentication failure that looks like a password problem.
fn qop_offers_auth(qop: Option<&str>) -> bool {
    qop.is_some_and(|q| q.split(',').any(|part| part.trim() == "auth"))
}

/// RFC 7616 §3.4.1 field quoting.
///
/// `qop`, `nc` and `algorithm` are `token` productions and MUST NOT be quoted
/// — strict servers reject `qop="auth"`. Everything else is a `quoted-string`
/// and MUST be.
///
/// The escaping is a SECURITY fix, not cosmetic: a username containing `"`, or
/// one ending in `\`, otherwise breaks out of the quoted string and injects
/// directives — reachable from a CSV data file driving a run. Stripping the
/// quotes instead (the older behaviour) silently corrupted the credential:
/// `ab"c` was signed as `abc`.
fn digest_field(key: &str, value: &str) -> String {
    match key {
        "qop" | "nc" | "algorithm" => format!("{key}={value}"),
        _ => format!(
            "{key}=\"{}\"",
            value.replace('\\', "\\\\").replace('"', "\\\"")
        ),
    }
}

/// Build the `Authorization: Digest …` header for a challenge.
///
/// Covers MD5, SHA-256 and SHA-512-256, each with and without `-sess`. Bruno
/// is MD5-only, so this breadth is the differentiator — which is also why it
/// is worth exporting rather than reimplementing.
///
/// The three cases the shape has to get right, all of them interop failures
/// when wrong:
///   1. `qop` offering `auth` — response uses the nc/cnonce form and the
///      header carries `qop`, `nc` and `cnonce`.
///   2. `qop` present but WITHOUT `auth` — fall back to the no-qop response
///      form and do NOT emit `qop`/`nc`.
///   3. no usable `qop` but a `-sess` algorithm — RFC 7616 §3.4.4 still
///      requires a cnonce (it is folded into HA1), so it is emitted even
///      though `nc` is not.
///
/// Field ORDER matches `signers.rs`'s long-standing output byte for byte, so
/// that delegating to this function is not observable on the wire.
pub fn digest_build_authorization(p: &DigestBuildParams<'_>) -> HeaderOut {
    let algorithm = p
        .algorithm
        .map(|a| a.to_ascii_uppercase())
        .unwrap_or_else(|| "MD5".to_string());
    let is_sess = algorithm.ends_with("-SESS");
    let use_qop = qop_offers_auth(p.qop);

    // The response is computed against the qop the header will actually
    // CLAIM, never against the challenge's raw list.
    let effective = DigestBuildParams {
        qop: if use_qop { Some("auth") } else { None },
        ..p.clone()
    };
    let response = digest_response_value(&effective, &algorithm);

    let mut fields: Vec<(&str, String)> = vec![
        ("username", p.username.to_string()),
        ("realm", p.realm.to_string()),
        ("nonce", p.nonce.to_string()),
        ("uri", p.uri.to_string()),
    ];
    if use_qop {
        fields.push(("qop", "auth".to_string()));
        fields.push(("nc", format!("{:08x}", p.nc)));
        fields.push(("cnonce", p.cnonce.to_string()));
    } else if is_sess {
        // Case 3: no nc, but the cnonce is load-bearing for HA1.
        fields.push(("cnonce", p.cnonce.to_string()));
    }
    fields.push(("response", response));
    // Only echo `algorithm` when the server named one (see DigestBuildParams).
    if p.algorithm.is_some() {
        fields.push(("algorithm", algorithm));
    }
    if let Some(opaque) = p.opaque {
        fields.push(("opaque", opaque.to_string()));
    }

    HeaderOut {
        name: "Authorization".to_string(),
        value: format!(
            "Digest {}",
            fields
                .iter()
                .map(|(k, v)| digest_field(k, v))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

// ── Hawk (hawk.1.header) ────────────────────────────────────────────────────

/// Everything needed to build a Hawk `Authorization` header.
///
/// `ts` and `nonce` are caller-supplied so a vector can be pinned; the signer
/// passes the host clock and a CSPRNG nonce.
#[derive(Debug, Clone)]
pub struct HawkBuildParams<'a> {
    /// HTTP method — uppercased internally.
    pub method: &'a str,
    /// Request-target: path + query.
    pub resource: &'a str,
    /// Host WITHOUT brackets for IPv6; the caller brackets if it must.
    pub host: &'a str,
    pub port: u16,
    pub id: &'a str,
    pub key: &'a str,
    /// `"sha256"` (default) or `"sha1"`.
    pub algorithm: Option<&'a str>,
    /// Unix seconds, as a string.
    pub ts: &'a str,
    pub nonce: &'a str,
    /// Application-specific data folded into the MAC. Empty when unused.
    pub ext: &'a str,
}

/// The Hawk normalized request string.
///
/// Field ORDER is the whole contract: scheme, ts, nonce, method, resource,
/// host, port, hash, ext — each followed by a newline. `ts` and `nonce` come
/// FIRST, immediately after the scheme line. An earlier implementation put
/// method/resource/host/port first and produced a MAC every Hawk server
/// rejects, which is why the order is spelled out rather than inferred.
pub fn hawk_normalized_string(p: &HawkBuildParams<'_>, hash: &str) -> String {
    let method = p.method.to_uppercase();
    let host = p.host.to_lowercase();
    format!(
        "hawk.1.header\n{}\n{}\n{method}\n{}\n{host}\n{}\n{hash}\n{}\n",
        p.ts, p.nonce, p.resource, p.port, p.ext
    )
}

/// Hawk request MAC = base64(HMAC(algorithm, key, normalized)).
///
/// Defaults to SHA-256; `"sha1"` selects the legacy variant. Anything else is
/// treated as SHA-256 rather than refused, matching the signer — a Hawk server
/// that wanted SHA-1 will reject the MAC, which is a loud failure at the wire.
pub fn hawk_mac(normalized: &str, key: &str, algorithm: Option<&str>) -> String {
    use base64::Engine as _;
    use hmac::digest::KeyInit as _;
    use hmac::{Hmac, Mac as _};
    use sha1::Sha1;
    let sha1 = algorithm.is_some_and(|a| a.eq_ignore_ascii_case("sha1"));
    if sha1 {
        let mut mac =
            Hmac::<Sha1>::new_from_slice(key.as_bytes()).expect("HMAC-SHA1 accepts any key length");
        mac.update(normalized.as_bytes());
        base64::engine::general_purpose::STANDARD.encode(mac.finalize().into_bytes())
    } else {
        let mut mac = Hmac::<Sha256>::new_from_slice(key.as_bytes())
            .expect("HMAC-SHA256 accepts any key length");
        mac.update(normalized.as_bytes());
        base64::engine::general_purpose::STANDARD.encode(mac.finalize().into_bytes())
    }
}

/// Build the `Authorization: Hawk …` header.
///
/// Payload validation (`hash`) is deliberately not implemented — the signer
/// has never sent one, and emitting an empty `hash=""` would be worse than
/// omitting it. The normalized string still carries the empty hash field,
/// because the spec's field COUNT is fixed.
pub fn hawk_build_header(p: &HawkBuildParams<'_>) -> HeaderOut {
    let normalized = hawk_normalized_string(p, "");
    let mac = hawk_mac(&normalized, p.key, p.algorithm);
    HeaderOut {
        name: "Authorization".to_string(),
        value: format!(
            "Hawk id=\"{}\", ts=\"{}\", nonce=\"{}\", mac=\"{}\"",
            p.id, p.ts, p.nonce, mac
        ),
    }
}

// ── AWS Signature Version 4 ─────────────────────────────────────────────────

// ── SigV4 service rules ─────────────────────────────────────────────────────
// TR-428: these were left in `signers.rs` by TR-426, which made them
// unreachable from `tropel-core-wasm` (`default-features = false` turns the
// `reqwest` feature, and therefore the whole `signers` module, off). A browser
// caller could reach `aws_sigv4_build_headers` but could NOT compute two of
// the inputs it requires — `canonical_uri` and the signing service — so the
// only way to call it from the web tier would have been to re-derive both in
// TypeScript. That is invariant #3, and `default_service`'s comment below
// records exactly what re-deriving it wrongly costs: a 403 on every S3
// request. They live here now.

const VIRTUAL_HOSTED_SERVICE_LABELS: &[&str] = &[
    "s3",
    "s3-control",
    "s3-object-lambda",
    "s3-outposts",
    "s3express",
    "execute-api",
    "es",
    "aoss",
    "cloudsearch",
];

pub fn default_service(host: &str) -> String {
    // Virtual-hosted AWS endpoints put the tenant BEFORE the service label
    // (examplebucket.s3.amazonaws.com, {api-id}.execute-api.{region}.
    // amazonaws.com, {domain}.{region}.es.amazonaws.com), so the first DNS
    // label is NOT the signing service (backlog line 60: the old code derived
    // `examplebucket` / `abc` / `search-x`, breaking the scope, the signing
    // key, and is_s3_family → double-encoded S3 path → 403 on everything).
    // For *.amazonaws.com hosts, scan labels RIGHT-TO-LEFT for a known
    // virtual-hosted service: the service label sits closest to the
    // amazonaws suffix, so this is also collision-robust when a tenant
    // happens to BE a service name (es.s3.amazonaws.com → s3, not es). The
    // S3 website/fips endpoints (bucket.s3-website-{region}…,
    // s3-fips…amazonaws.com) still sign as s3. Everything else keeps the
    // first-label rule (s3.us-west-2.amazonaws.com → s3; non-AWS hosts keep
    // their first label).
    let is_aws = host.ends_with(".amazonaws.com")
        || host.ends_with(".amazonaws.com.cn")
        || host == "amazonaws.com";
    if is_aws {
        for label in host.split('.').rev() {
            if label == "amazonaws" || label == "com" || label == "cn" {
                continue;
            }
            if VIRTUAL_HOSTED_SERVICE_LABELS.contains(&label) {
                return label.to_string();
            }
            if label.starts_with("s3-website-") || label == "s3-fips" {
                return "s3".to_string();
            }
        }
    }
    host.split('.').next().unwrap_or(host).to_string()
}

/// Map a service name to its SigV4 signing name. Most services sign with
/// their own name, but AWS S3 Control uses `s3` as the signing name despite
/// the endpoint prefix being `s3-control` (backlog line 240).
pub fn signing_name(service: &str) -> &str {
    match service {
        "s3-control" | "s3control" => "s3",
        other => other,
    }
}

/// Canonical URI for SigV4.
///
/// AWS requires DOUBLE URI-encoding of the absolute path for every service
/// EXCEPT the S3 family (s3, s3control, s3-object-lambda, s3-outposts,
/// s3express), which sign the single-encoded path exactly as sent. The `url`
/// crate already single-encodes `Url::path()` with the RFC 3986 unreserved
/// rules, so re-encoding each segment yields the required second encoding
/// for non-S3 services (`%` is not unreserved → `%25`). Empty segments
/// (leading/trailing slash, `//`) are preserved; an empty path becomes `/`.
pub fn sigv4_canonical_uri(path: &str, service: &str) -> String {
    if is_s3_family(service) {
        return if path.is_empty() {
            "/".to_string()
        } else {
            path.to_string()
        };
    }
    if path.is_empty() {
        return "/".to_string();
    }
    // Backlog line 240: normalize consecutive slashes — AWS's official
    // test suite expects //prod/users → /prod/users. Without this, the
    // classic base-URL-ends-in-/ join produces a double-slash that fails
    // signature verification with a 403.
    // TR-603: single replace("//","/") only handles pairs; use a loop
    // for runs of 3+ consecutive slashes.
    let mut normalized = path.to_string();
    while normalized.contains("//") {
        normalized = normalized.replace("//", "/");
    }
    let encoded: Vec<String> = normalized
        .split('/')
        .map(percent_encode_unreserved)
        .collect();
    encoded.join("/")
}

/// True for the S3 family of services, which sign the single-encoded path.
///
/// Matches both spellings of S3 Control's signing name ("s3-control" is what
/// `default_service` derives from `s3-control.<region>.amazonaws.com`; some
/// tools emit the un-hyphenated "s3control").
pub fn is_s3_family(service: &str) -> bool {
    matches!(
        service,
        "s3" | "s3control" | "s3-control" | "s3-object-lambda" | "s3-outposts" | "s3express"
    )
}

/// Duplicates are allowed and are what the multi-value comma-join operates on.
#[derive(Debug, Clone)]
/// Everything needed to build the SigV4 headers.
///
/// `headers` is the request's headers in INSERTION order, names as sent.
pub struct AwsSigV4BuildParams<'a> {
    /// Uppercase HTTP method.
    pub method: &'a str,
    /// Path, un-encoded (the canonicalizer encodes it).
    pub path: &'a str,
    /// Raw query string WITHOUT the leading `?`. Empty when there is none.
    pub query: &'a str,
    /// Canonical host — `host[:port]`, port omitted when default for scheme.
    pub host: &'a str,
    pub headers: &'a [(String, String)],
    /// `None` signs UNSIGNED-PAYLOAD.
    pub body: Option<&'a [u8]>,
    pub access_key: &'a str,
    pub secret_key: &'a str,
    pub session_token: Option<&'a str>,
    pub region: &'a str,
    /// The service label used for BOTH the canonical URI rule and the scope.
    pub service: &'a str,
    /// `YYYYMMDDTHHMMSSZ`.
    pub amz_date: &'a str,
    /// `YYYYMMDD` — the scope's date component.
    pub date_stamp: &'a str,
}

/// AWS "Trimall": collapse runs of spaces to one and trim the ends.
pub fn trim_all(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Canonical query string: pairs sorted by RAW bytes, joined `k=v` with `&`.
///
/// Takes the raw query rather than a parsed URL deliberately — re-encoding a
/// value that is already percent-encoded double-encodes it, and AWS signs the
/// bytes that are on the wire.
pub fn sigv4_canonical_query(query: &str) -> String {
    let mut pairs: Vec<(&str, &str)> = query
        .split('&')
        .filter(|p| !p.is_empty())
        .map(|p| match p.split_once('=') {
            Some((k, v)) => (k, v),
            None => (p, ""),
        })
        .collect();
    pairs.sort();
    pairs
        .iter()
        .map(|(k, v)| format!("{k}={v}"))
        .collect::<Vec<_>>()
        .join("&")
}

/// Canonical headers, sorted by lowercased name.
///
/// Multi-value headers are joined with a BARE COMMA and no space, each value
/// Trimall'd. `", "` produces a different canonical hash and therefore a 403
/// `SignatureDoesNotMatch` on any duplicated header — that was a real bug, so
/// the join is spelled out rather than reached for.
///
/// `authorization` is excluded (it is what we are building). Non-UTF-8 values
/// cannot appear in a canonical request and are skipped rather than panicking.
pub fn sigv4_canonical_headers(
    host: &str,
    headers: &[(String, String)],
    payload_hash: &str,
    amz_date: &str,
    session_token: Option<&str>,
) -> Vec<(String, String)> {
    use std::collections::BTreeMap;
    // BTreeMap gives sorted keys for free.
    let mut grouped: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (name, value) in headers {
        let key = name.to_ascii_lowercase();
        if key == "authorization" {
            continue;
        }
        grouped.entry(key).or_default().push(trim_all(value));
    }
    let mut out: BTreeMap<String, String> = grouped
        .into_iter()
        .filter(|(_, v)| !v.is_empty())
        .map(|(k, v)| (k, v.join(",")))
        .collect();

    out.insert("host".to_string(), host.to_string());
    out.insert("x-amz-content-sha256".to_string(), payload_hash.to_string());
    out.insert("x-amz-date".to_string(), amz_date.to_string());
    if let Some(token) = session_token {
        out.insert("x-amz-security-token".to_string(), token.to_string());
    }
    out.into_iter().collect()
}

fn hmac_sha256_bytes(key: &[u8], data: &[u8]) -> Vec<u8> {
    use hmac::digest::KeyInit as _;
    use hmac::{Hmac, Mac as _};
    let mut mac = Hmac::<Sha256>::new_from_slice(key).expect("HMAC-SHA256 accepts any key length");
    mac.update(data);
    mac.finalize().into_bytes().to_vec()
}

/// Hex HMAC-SHA256.
pub fn hex_hmac_sha256(key: &[u8], data: &[u8]) -> String {
    hex::encode(hmac_sha256_bytes(key, data))
}

/// The SigV4 derived signing key: HMAC chain over date → region → service.
///
/// Uncached here on purpose. `signers.rs` keeps its process-wide cache around
/// this call (the key changes only at UTC midnight, so caching saves four
/// chained HMACs per request); a browser embedder signs one request at a time
/// and does not need it. Caching inside would put a global mutex in the wasm
/// tier for no gain.
pub fn derive_signing_key(secret: &str, date: &str, region: &str, service: &str) -> Vec<u8> {
    let k_date = hmac_sha256_bytes(format!("AWS4{secret}").as_bytes(), date.as_bytes());
    let k_region = hmac_sha256_bytes(&k_date, region.as_bytes());
    let k_service = hmac_sha256_bytes(&k_region, service.as_bytes());
    hmac_sha256_bytes(&k_service, b"aws4_request")
}

/// Everything SigV4 attaches: the `Authorization` header plus the `x-amz-*`
/// headers that are part of the signature and must therefore also be sent.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SigV4Out {
    pub headers: Vec<HeaderOut>,
    /// Exposed for tests and for anyone diffing a 403.
    pub canonical_request: String,
    pub string_to_sign: String,
}

/// Build the SigV4 headers.
///
/// `canonical_uri` is supplied by the caller because the encoding rule is
/// service-dependent — S3 signs the path single-encoded, every other service
/// double-encodes it — and that rule lives with the service derivation in
/// `signers.rs`.
pub fn aws_sigv4_build_headers(
    p: &AwsSigV4BuildParams<'_>,
    canonical_uri: &str,
    signing_service: &str,
    signing_key: &[u8],
) -> SigV4Out {
    let payload_hash = match p.body {
        Some(bytes) => hex_sha256(bytes),
        None => "UNSIGNED-PAYLOAD".to_string(),
    };
    let canonical_query = sigv4_canonical_query(p.query);
    let headers = sigv4_canonical_headers(
        p.host,
        p.headers,
        &payload_hash,
        p.amz_date,
        p.session_token,
    );
    let signed_headers = headers
        .iter()
        .map(|(k, _)| k.as_str())
        .collect::<Vec<_>>()
        .join(";");
    let canonical_headers = headers
        .iter()
        .map(|(k, v)| format!("{k}:{v}\n"))
        .collect::<Vec<_>>()
        .concat();

    let canonical_request = format!(
        "{}\n{canonical_uri}\n{canonical_query}\n{canonical_headers}\n{signed_headers}\n{payload_hash}",
        p.method.to_uppercase()
    );
    let scope = format!(
        "{}/{}/{signing_service}/aws4_request",
        p.date_stamp, p.region
    );
    let string_to_sign = format!(
        "AWS4-HMAC-SHA256\n{}\n{scope}\n{}",
        p.amz_date,
        hex_sha256(canonical_request.as_bytes())
    );
    let signature = hex_hmac_sha256(signing_key, string_to_sign.as_bytes());

    let mut out = vec![HeaderOut {
        name: "Authorization".to_string(),
        value: format!(
            "AWS4-HMAC-SHA256 Credential={}/{scope}, SignedHeaders={signed_headers}, Signature={signature}",
            p.access_key
        ),
    }];
    // These are IN the signature, so they must reach the wire too.
    out.push(HeaderOut {
        name: "x-amz-date".to_string(),
        value: p.amz_date.to_string(),
    });
    out.push(HeaderOut {
        name: "x-amz-content-sha256".to_string(),
        value: payload_hash,
    });
    if let Some(token) = p.session_token {
        out.push(HeaderOut {
            name: "x-amz-security-token".to_string(),
            value: token.to_string(),
        });
    }
    SigV4Out {
        headers: out,
        canonical_request,
        string_to_sign,
    }
}

// ─────────────────────────── OAuth1 (RFC 5849) ───────────────────────────

/// RFC 3986 unreserved characters: `A-Z a-z 0-9 - . _ ~` stay unencoded.
///
/// RFC 5849 §3.6 mandates exactly this set for every OAuth1 encoding — the
/// base string, the signing key and the header parameters. `signers.rs` had
/// its own identical copy; a single definition is the point of this module,
/// because a percent-encoding set that drifts by one character produces a
/// signature the server rejects with no useful diagnostic.
const RFC3986_UNRESERVED: AsciiSet = NON_ALPHANUMERIC
    .remove(b'-')
    .remove(b'.')
    .remove(b'_')
    .remove(b'~');

/// The signature methods [`oauth1_build_header`] implements.
///
/// Exported so the caller's "unsupported method" guard and the builder's own
/// dispatch read from ONE list. When they were separate, adding a method to
/// one and not the other was a silent downgrade — the TR-004/TR-409 failure
/// shape, where an unsupported method quietly signs as HMAC-SHA1.
pub const OAUTH1_SIGNATURE_METHODS: [&str; 3] = ["HMAC-SHA1", "HMAC-SHA256", "HMAC-SHA512"];

/// Whether `method` (case-insensitive) is one of [`OAUTH1_SIGNATURE_METHODS`].
pub fn oauth1_is_supported_signature_method(method: &str) -> bool {
    OAUTH1_SIGNATURE_METHODS
        .iter()
        .any(|m| m.eq_ignore_ascii_case(method))
}

/// RFC 3986 §2.3 percent-encoding: everything except `A-Z a-z 0-9 - . _ ~`.
///
/// Shared, not per-scheme: RFC 5849 §3.6 (OAuth1) and SigV4's canonical URI
/// both specify exactly this set. Two copies of a percent-encoding set is how
/// two signers start disagreeing by one character, which is a 403 with no
/// useful diagnostic.
pub fn percent_encode_unreserved(value: &str) -> String {
    utf8_percent_encode(value, &RFC3986_UNRESERVED).to_string()
}

/// RFC 5849 §3.4.1.1 signature base string.
///
/// `HTTPMethod & "&" & baseURI & "&" & normalizedParams` where the separators
/// are literal `&` characters (ASCII 38), NOT newlines. Each component is
/// percent-encoded per §3.6; params are sorted by encoded name, then encoded
/// value (§3.4.1.3.2), which is why the sort happens AFTER encoding.
pub fn oauth1_base_string(method: &str, base_uri: &str, params: &[(String, String)]) -> String {
    let mut encoded: Vec<(String, String)> = params
        .iter()
        .map(|(k, v)| (percent_encode_unreserved(k), percent_encode_unreserved(v)))
        .collect();
    encoded.sort();
    let param_string = encoded
        .iter()
        .map(|(k, v)| format!("{k}={v}"))
        .collect::<Vec<_>>()
        .join("&");
    format!(
        "{}&{}&{}",
        method.to_uppercase(),
        percent_encode_unreserved(base_uri),
        percent_encode_unreserved(&param_string)
    )
}

/// RFC 5849 §3.4.2 HMAC signature over the base string, base64-encoded.
///
/// Signing key = `percent_encode_unreserved(consumer_secret) & percent_encode_unreserved(token_secret)` — the `&` is
/// present even when the token secret is empty (two-legged OAuth), which is
/// why the caller passes `""` rather than omitting it.
///
/// Returns `None` for a method outside [`OAUTH1_SIGNATURE_METHODS`] rather
/// than falling back to HMAC-SHA1: a silent downgrade is the exact failure
/// TR-409 exists to prevent.
pub fn oauth1_signature(
    base_string: &str,
    consumer_secret: &str,
    token_secret: &str,
    signature_method: &str,
) -> Option<String> {
    let key = format!(
        "{}&{}",
        percent_encode_unreserved(consumer_secret),
        percent_encode_unreserved(token_secret)
    );
    // One macro rather than a generic: `hmac::Hmac<D>` needs bounds that are
    // awkward to name across digest crates, and three explicit arms match how
    // the rest of this module dispatches.
    macro_rules! sign_with {
        ($alg:ty) => {{
            let mut mac = <Hmac<$alg> as KeyInit>::new_from_slice(key.as_bytes())
                .expect("HMAC accepts any key length");
            mac.update(base_string.as_bytes());
            base64::engine::general_purpose::STANDARD.encode(mac.finalize().into_bytes())
        }};
    }
    Some(match signature_method.to_ascii_uppercase().as_str() {
        "HMAC-SHA1" => sign_with!(Sha1),
        "HMAC-SHA256" => sign_with!(Sha256),
        "HMAC-SHA512" => sign_with!(Sha512),
        _ => return None,
    })
}

/// Everything [`oauth1_build_header`] needs, as plain data.
pub struct OAuth1BuildParams<'a> {
    /// HTTP method; uppercased by the builder.
    pub method: &'a str,
    /// RFC 5849 §3.4.1.2 base string URI: `scheme://host[:port]/path`, with
    /// the query and fragment stripped and the default port omitted. The
    /// caller derives this because it needs the parsed URL.
    pub base_uri: &'a str,
    /// Protocol parameters from the query string and, when the body is
    /// `application/x-www-form-urlencoded`, from the body — already
    /// percent-DECODED (§3.4.1.3.1). The `oauth_*` params are added by the
    /// builder; do not pass them here.
    pub request_params: &'a [(String, String)],
    pub consumer_key: &'a str,
    pub consumer_secret: &'a str,
    pub token: Option<&'a str>,
    pub token_secret: Option<&'a str>,
    /// One of [`OAUTH1_SIGNATURE_METHODS`], any case.
    pub signature_method: &'a str,
    pub nonce: &'a str,
    /// Seconds since the epoch, as a decimal string.
    pub timestamp: &'a str,
}

/// An OAuth1 `Authorization` header plus the base string it was signed over.
pub struct OAuth1Out {
    pub header: HeaderOut,
    /// Returned for the differential harness and for diagnosing a 401: a
    /// rejected OAuth1 request is almost always a base-string mismatch, and
    /// without this the only way to see it is a debugger.
    pub base_string: String,
}

/// Build the OAuth1 `Authorization` header (RFC 5849 §3.5.1).
///
/// Returns `None` when `signature_method` is unsupported, so the caller can
/// raise its own error naming the supported set.
pub fn oauth1_build_header(p: &OAuth1BuildParams<'_>) -> Option<OAuth1Out> {
    let method_str = p.signature_method.to_ascii_uppercase();
    if !oauth1_is_supported_signature_method(&method_str) {
        return None;
    }

    let mut oauth: Vec<(String, String)> = vec![
        ("oauth_consumer_key".to_string(), p.consumer_key.to_string()),
        ("oauth_nonce".to_string(), p.nonce.to_string()),
        ("oauth_signature_method".to_string(), method_str.clone()),
        ("oauth_timestamp".to_string(), p.timestamp.to_string()),
        ("oauth_version".to_string(), "1.0".to_string()),
    ];
    if let Some(token) = p.token {
        oauth.push(("oauth_token".to_string(), token.to_string()));
    }

    // §3.4.1.3: the base string signs the request params AND the oauth params
    // together. The header below carries only the oauth ones.
    let mut all_params: Vec<(String, String)> = p.request_params.to_vec();
    all_params.extend(oauth.clone());

    let base_string = oauth1_base_string(p.method, p.base_uri, &all_params);
    let signature = oauth1_signature(
        &base_string,
        p.consumer_secret,
        p.token_secret.unwrap_or(""),
        &method_str,
    )?;

    let mut header_params = oauth;
    header_params.push(("oauth_signature".to_string(), signature));
    header_params.sort();
    let value = header_params
        .iter()
        .map(|(k, v)| {
            format!(
                "{}=\"{}\"",
                percent_encode_unreserved(k),
                percent_encode_unreserved(v)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");

    Some(OAuth1Out {
        header: HeaderOut {
            name: "Authorization".to_string(),
            value: format!("OAuth {value}"),
        },
        base_string,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn params<'a>(algorithm: Option<&'a str>, qop: Option<&'a str>) -> DigestBuildParams<'a> {
        DigestBuildParams {
            username: "Mufasa",
            password: "Circle Of Life",
            method: "GET",
            uri: "/dir/index.html",
            realm: "testrealm@host.com",
            nonce: "dcd98b7102dd2f0e8b11d0f600bfb0c093",
            nc: 1,
            cnonce: "0a4f113b",
            qop,
            algorithm,
            opaque: Some("5ccc069c403ebaf9f0171e9517f40e41"),
        }
    }

    #[test]
    fn rfc_2617_md5_qop_auth_vector() {
        // The canonical RFC 2617 §3.5 example. A published vector is the point:
        // it cannot drift with the implementation the way a self-generated
        // expectation can.
        let out = digest_response_value(&params(Some("MD5"), Some("auth")), "MD5");
        assert_eq!(out, "6629fae49393a05397450978507c4ef1");
    }

    #[test]
    fn sess_changes_the_response_and_the_base_hash_does_not() {
        // `-sess` folds nonce+cnonce into HA1, so the response MUST differ …
        let plain = digest_response_value(&params(Some("MD5"), Some("auth")), "MD5");
        let sess = digest_response_value(&params(Some("MD5-sess"), Some("auth")), "MD5-SESS");
        assert_ne!(plain, sess);
        // … while the hash function itself stays MD5 (32 hex chars).
        assert_eq!(sess.len(), 32);
    }

    #[test]
    fn sha256_and_sha512_256_are_distinct_and_correctly_sized() {
        let s256 = digest_response_value(&params(Some("SHA-256"), Some("auth")), "SHA-256");
        let s512 = digest_response_value(&params(Some("SHA-512-256"), Some("auth")), "SHA-512-256");
        assert_eq!(s256.len(), 64);
        assert_eq!(s512.len(), 64);
        // SHA-512/256 is a separate hash, not truncated SHA-512 — if it were
        // implemented as a truncation these would still differ, but the
        // published-vector test above is what pins the actual bytes.
        assert_ne!(s256, s512);
    }

    #[test]
    fn algorithm_is_echoed_only_when_the_server_named_one() {
        // Some strict servers reject an explicit `algorithm=MD5`.
        let named = digest_build_authorization(&params(Some("MD5"), Some("auth")));
        assert!(named.value.contains("algorithm=MD5"));
        let omitted = digest_build_authorization(&params(None, Some("auth")));
        assert!(!omitted.value.contains("algorithm="), "{}", omitted.value);
        // …and it still hashes as MD5, which is RFC 7616's default.
        assert!(omitted.value.contains("response=\""));
    }

    #[test]
    fn qop_controls_nc_and_cnonce() {
        // Without qop the response formula is the older 3-part form and the
        // header must NOT carry nc/cnonce — sending them anyway is a common
        // interop failure.
        let with = digest_build_authorization(&params(Some("MD5"), Some("auth")));
        assert!(with.value.contains("nc=00000001") && with.value.contains("cnonce="));
        let without = digest_build_authorization(&params(Some("MD5"), None));
        assert!(!without.value.contains("nc="), "{}", without.value);
        assert!(!without.value.contains("cnonce="), "{}", without.value);
    }

    #[test]
    fn qop_is_a_list_and_only_auth_counts() {
        // `qop="auth,auth-int"` must be honoured as auth …
        let mut p = params(Some("MD5"), Some("auth,auth-int"));
        let out = digest_build_authorization(&p);
        assert!(out.value.contains("qop=auth"), "{}", out.value);
        assert!(out.value.contains("nc=00000001"));

        // … and the header must claim plain `auth`, never echo the raw list.
        assert!(!out.value.contains("auth-int"), "{}", out.value);

        // A challenge offering ONLY auth-int falls back to the no-qop form:
        // auth-int folds the entity body into HA2, which we do not compute, so
        // claiming it would be an auth failure that looks like a bad password.
        p.qop = Some("auth-int");
        let fallback = digest_build_authorization(&p);
        assert!(!fallback.value.contains("qop="), "{}", fallback.value);
        assert!(!fallback.value.contains("nc="), "{}", fallback.value);
    }

    #[test]
    fn sess_without_qop_still_carries_a_cnonce() {
        // RFC 7616 §3.4.4: `-sess` folds the cnonce into HA1, so it is
        // load-bearing even when there is no qop — and `nc` still is not.
        let out = digest_build_authorization(&params(Some("MD5-sess"), None));
        assert!(out.value.contains("cnonce=\"0a4f113b\""), "{}", out.value);
        assert!(!out.value.contains("nc="), "{}", out.value);

        // Non-sess without qop carries neither.
        let plain = digest_build_authorization(&params(Some("MD5"), None));
        assert!(!plain.value.contains("cnonce="), "{}", plain.value);
    }

    #[test]
    fn the_response_is_computed_against_the_qop_the_header_claims() {
        // The subtle one. With `auth-int` only, the header drops qop — so the
        // RESPONSE must use the no-qop formula too. Computing the nc/cnonce
        // form while advertising no qop is a silent mismatch the server
        // rejects as a bad password.
        let auth_int = digest_build_authorization(&params(Some("MD5"), Some("auth-int")));
        let no_qop = digest_build_authorization(&params(Some("MD5"), None));
        let resp = |h: &HeaderOut| {
            h.value
                .split("response=\"")
                .nth(1)
                .and_then(|r| r.split('"').next())
                .unwrap()
                .to_string()
        };
        assert_eq!(resp(&auth_int), resp(&no_qop));
    }

    #[test]
    fn rfc_7616_published_vectors_md5_and_sha256() {
        // Moved here from `signers.rs` with the delegation (TR-424): the
        // computation lives here now, so its published vectors do too.
        //
        // NOTE: RFC 7616 spells the password "Circle of Life" (lowercase o)
        // while RFC 2617 uses "Circle Of Life". The two RFCs genuinely
        // differ — keep each test faithful to its own source.
        let vector = |algorithm: &'static str| DigestBuildParams {
            username: "Mufasa",
            password: "Circle of Life",
            method: "GET",
            uri: "/dir/index.html",
            realm: "http-auth@example.org",
            nonce: "7ypf/xlj9XXwfDPEoM4URrv/xwf94BcCAzFZH4GiTo0v",
            nc: 1,
            cnonce: "f2/wE4q74E6zIJEtWaHKaf5wv/H5QzzpXusqGemxURZJ",
            qop: Some("auth"),
            algorithm: Some(algorithm),
            opaque: None,
        };

        assert_eq!(
            digest_response_value(&vector("MD5"), "MD5"),
            "8ca523f5e9506fed4657c9700eebdbec",
            "RFC 7616 §3.9.1 published MD5 response"
        );
        assert_eq!(
            digest_response_value(&vector("SHA-256"), "SHA-256"),
            "753927fa0e85d155564e2e272a28d1802ca10daf4496794697cf8db5856cb6c1",
            "RFC 7616 §3.9.1 published SHA-256 response"
        );
    }

    #[test]
    fn ha1_and_ha2_match_the_published_intermediates() {
        // The RFC publishes the intermediates too. Asserting them separately
        // means a failure says WHICH half is wrong, instead of only that the
        // final response differs.
        assert_eq!(
            digest_with("Mufasa:testrealm@host.com:Circle Of Life", "MD5"),
            "939e7578ed9e3c518a452acee763bce9",
            "RFC 2617 §3.5 HA1"
        );
        assert_eq!(
            digest_with("GET:/dir/index.html", "MD5"),
            "39aff3a2bab6126f332b942af96d3366",
            "RFC 2617 §3.5 HA2"
        );
    }

    #[test]
    fn quoted_string_values_are_escaped_not_stripped() {
        // SECURITY, not cosmetics. A username ending in a backslash otherwise
        // terminates the quoted-string early and the rest of the header is
        // read as directives — reachable from a CSV data file driving a run.
        // Stripping the quotes instead (the behaviour before P2 line 180)
        // silently signed a DIFFERENT credential: `ab"c` became `abc`.
        let mut p = params(Some("MD5"), Some("auth"));
        p.username = r#"ab"c"#;
        let out = digest_build_authorization(&p);
        assert!(
            out.value.contains(r#"username="ab\"c""#),
            "quote must be escaped, not stripped: {}",
            out.value
        );

        p.username = r"trailing\";
        let out = digest_build_authorization(&p);
        assert!(
            out.value.contains(r#"username="trailing\\""#),
            "backslash must be escaped so it cannot break out: {}",
            out.value
        );
    }

    #[test]
    fn token_fields_are_unquoted_and_the_rest_are_quoted() {
        // RFC 7616 §3.4.1: qop/nc/algorithm are `token`, and strict servers
        // reject `qop="auth"`. Everything else is `quoted-string`.
        let out = digest_build_authorization(&params(Some("MD5"), Some("auth"))).value;
        assert!(out.contains("qop=auth,"), "{out}");
        assert!(out.contains("nc=00000001,"), "{out}");
        assert!(out.contains("algorithm=MD5"), "{out}");
        assert!(out.contains(r#"realm="testrealm@host.com""#), "{out}");
        assert!(out.contains(r#"cnonce="0a4f113b""#), "{out}");
    }

    #[test]
    fn field_order_is_the_wire_order() {
        // Pinned because `signers.rs` delegates here: a reordering would be
        // observable on the wire even though every field is still present.
        let out = digest_build_authorization(&params(Some("MD5"), Some("auth"))).value;
        let order: Vec<&str> = [
            "username",
            "realm",
            "nonce",
            "uri",
            "qop",
            "nc",
            "cnonce",
            "response",
            "algorithm",
            "opaque",
        ]
        .into_iter()
        .filter(|k| out.contains(&format!("{k}=")))
        .collect();
        let positions: Vec<usize> = order
            .iter()
            .map(|k| out.find(&format!("{k}=")).unwrap())
            .collect();
        let mut sorted = positions.clone();
        sorted.sort_unstable();
        assert_eq!(positions, sorted, "fields out of wire order: {out}");
    }

    // ── Hawk ─────────────────────────────────────────────────────────────

    fn hawk<'a>(algorithm: Option<&'a str>) -> HawkBuildParams<'a> {
        HawkBuildParams {
            method: "GET",
            resource: "/resource/1?b=1&a=2",
            host: "example.com",
            port: 8000,
            id: "dh37fgj492je",
            key: "werxhqb98rpaxn39848xrunpaw3489ruxnpa98w4rxn",
            algorithm,
            ts: "1353832234",
            nonce: "j4h3g2",
            ext: "some-app-ext-data",
        }
    }

    #[test]
    fn hawk_normalized_string_matches_the_spec_vector() {
        // The published example from the Hawk spec / mozilla-hawk's own
        // README. Field ORDER is the whole contract here: ts and nonce come
        // FIRST, right after the scheme line. An earlier implementation put
        // method/resource/host/port first and produced a MAC every Hawk
        // server rejects — a bug a length check would never have caught.
        let out = hawk_normalized_string(&hawk(None), "");
        assert_eq!(
            out,
            "hawk.1.header\n1353832234\nj4h3g2\nGET\n/resource/1?b=1&a=2\nexample.com\n8000\n\nsome-app-ext-data\n"
        );
    }

    #[test]
    fn hawk_mac_matches_the_published_vector() {
        // Hawk spec §3.2.1 example → the published MAC for the string above.
        let normalized = hawk_normalized_string(&hawk(None), "");
        assert_eq!(
            hawk_mac(&normalized, hawk(None).key, None),
            "6R4rV5iE+NPoym+WwjeHzjAGXUtLNIxmo1vpMofpLAE="
        );
    }

    // ── SigV4 ────────────────────────────────────────────────────────────

    #[test]
    fn sigv4_canonical_query_preserves_raw_bytes() {
        // Regression, ported with the move (TR-426). `query_pairs()`
        // form-decodes `+` to a space and re-encoding writes `%20` back —
        // AWS canonicalizes the RAW bytes, so both must survive untouched.
        // Sorted by raw key then value: `%` (0x25) sorts before `+` (0x2B).
        assert_eq!(
            sigv4_canonical_query("a=b+c&z=1&a=b%20c"),
            "a=b%20c&a=b+c&z=1"
        );
        // Duplicate keys sort by value; valueless params keep their `=`.
        assert_eq!(sigv4_canonical_query("flag&a=2&a=1"), "a=1&a=2&flag=");
        assert_eq!(sigv4_canonical_query(""), "");
    }

    #[test]
    fn sigv4_trimall_and_multi_value_join() {
        // AWS joins duplicated headers with a BARE comma — no space — and
        // Trimall collapses internal runs of whitespace. `", "` yields a
        // different canonical hash and therefore a 403 SignatureDoesNotMatch
        // on any request carrying a duplicated header.
        assert_eq!(trim_all("  a   b  "), "a b");
        let headers = vec![
            ("X-Multi".to_string(), "  one  ".to_string()),
            ("x-multi".to_string(), "two".to_string()),
        ];
        let out =
            sigv4_canonical_headers("example.com", &headers, "HASH", "20130524T000000Z", None);
        let multi = out
            .iter()
            .find(|(k, _)| k == "x-multi")
            .expect("x-multi present");
        assert_eq!(multi.1, "one,two");
        // authorization is excluded — it is what we are building.
        let with_auth = vec![("Authorization".to_string(), "old".to_string())];
        let out = sigv4_canonical_headers("example.com", &with_auth, "H", "T", None);
        assert!(!out.iter().any(|(k, _)| k == "authorization"), "{out:?}");
    }

    #[test]
    fn sigv4_session_token_is_signed_when_present() {
        let out = sigv4_canonical_headers("example.com", &[], "H", "T", Some("tok"));
        assert!(out
            .iter()
            .any(|(k, v)| k == "x-amz-security-token" && v == "tok"));
        let without = sigv4_canonical_headers("example.com", &[], "H", "T", None);
        assert!(!without.iter().any(|(k, _)| k == "x-amz-security-token"));
    }

    #[test]
    fn hawk_payload_hash_vector() {
        // Hawk API.md "Payload Validation": the same request WITH a payload
        // hash. Ported from `signers.rs` with the delegation (TR-425) — a
        // distinct published vector from the empty-hash one above, and the
        // only thing that pins the `hash` field's position in the normalized
        // string. `hawk_build_header` never sends one, but the normalizer
        // must still place it correctly for anything that does.
        let mut p = hawk(None);
        p.method = "POST";
        let normalized = hawk_normalized_string(&p, "Yi9LfIIFRtBEPt74PVmbTF/xVAwPn7ub15ePICfgnuY=");
        assert_eq!(
            hawk_mac(&normalized, p.key, None),
            "aSe1DERmZuRl3pI36/9BdZmnErTw3sNzOOAUlfeKjVw="
        );
    }

    #[test]
    fn hawk_method_uppercases_and_host_lowercases() {
        // Both are normalization the spec requires; getting either wrong
        // changes the MAC without changing anything visible in the header.
        let mut p = hawk(None);
        p.method = "get";
        p.host = "EXAMPLE.com";
        assert_eq!(
            hawk_normalized_string(&p, ""),
            hawk_normalized_string(&hawk(None), "")
        );
    }

    #[test]
    fn hawk_sha1_differs_from_sha256_and_unknown_falls_back() {
        let n = hawk_normalized_string(&hawk(None), "");
        let k = hawk(None).key;
        let sha256 = hawk_mac(&n, k, None);
        let sha1 = hawk_mac(&n, k, Some("sha1"));
        assert_ne!(sha256, sha1);
        // Case-insensitive, and an unrecognised algorithm falls back to
        // SHA-256 rather than refusing — the server rejects the MAC, which is
        // a loud failure at the wire rather than a silent local one.
        assert_eq!(hawk_mac(&n, k, Some("SHA1")), sha1);
        assert_eq!(hawk_mac(&n, k, Some("md5")), sha256);
    }

    #[test]
    fn hawk_header_carries_id_ts_nonce_and_mac() {
        let out = hawk_build_header(&hawk(None));
        assert!(
            out.value.starts_with("Hawk id=\"dh37fgj492je\""),
            "{}",
            out.value
        );
        assert!(out.value.contains("ts=\"1353832234\""), "{}", out.value);
        assert!(out.value.contains("nonce=\"j4h3g2\""), "{}", out.value);
        assert!(out.value.contains("mac=\""), "{}", out.value);
        // No payload hash is sent, so none is advertised — an empty
        // `hash=""` would be worse than omitting it.
        assert!(!out.value.contains("hash="), "{}", out.value);
    }

    #[test]
    fn nc_is_eight_hex_digits() {
        let mut p = params(Some("MD5"), Some("auth"));
        p.nc = 255;
        assert!(digest_build_authorization(&p).value.contains("nc=000000ff"));
    }
    // ── OAuth1 ──────────────────────────────────────────────────────────────

    #[test]
    fn oauth1_every_listed_method_actually_dispatches() {
        // TR-427: `signers.rs` now admits a signature method by asking
        // `oauth1_is_supported_signature_method`, and `oauth1_signature`
        // dispatches on a separate `match`. That is a coupling this refactor
        // created: adding a method to the list without adding a match arm
        // would let the guard pass and then fail at the builder with a
        // confusing second error. Assert the two agree in both directions.
        for method in OAUTH1_SIGNATURE_METHODS {
            assert!(
                oauth1_is_supported_signature_method(method),
                "{method} is listed but the predicate rejects it"
            );
            assert!(
                oauth1_signature("base", "cs", "ts", method).is_some(),
                "{method} is listed but `oauth1_signature` has no arm for it"
            );
        }
        // And the converse: unsupported methods must return None, NOT fall
        // back to HMAC-SHA1. A silent downgrade is the TR-004/TR-409 shape.
        for method in ["RSA-SHA1", "RSA-SHA256", "PLAINTEXT", "HMAC-MD5", ""] {
            assert!(
                !oauth1_is_supported_signature_method(method),
                "{method} must not be treated as supported"
            );
            assert!(
                oauth1_signature("base", "cs", "ts", method).is_none(),
                "{method} must not produce a signature"
            );
        }
    }

    #[test]
    fn oauth1_signature_methods_produce_distinct_signatures() {
        // The three arms are generated by one macro differing only in the
        // digest type. A copy-paste slip that passed `Sha256` twice would
        // leave every test above green — they never compare the arms against
        // each other — while silently signing SHA-512 requests with SHA-256.
        let sigs: Vec<String> = OAUTH1_SIGNATURE_METHODS
            .iter()
            .map(|m| oauth1_signature("base-string", "cs", "ts", m).expect("listed method"))
            .collect();
        for (i, a) in sigs.iter().enumerate() {
            for (j, b) in sigs.iter().enumerate().skip(i + 1) {
                assert_ne!(
                    a, b,
                    "{} and {} produced the same signature — the macro arms are not distinct",
                    OAUTH1_SIGNATURE_METHODS[i], OAUTH1_SIGNATURE_METHODS[j]
                );
            }
        }
        // Lengths follow the digest, so a wrong arm is visible even if two
        // digests somehow collided.
        assert_eq!(
            sigs.iter().map(|s| s.len()).collect::<Vec<_>>(),
            vec![28, 44, 88],
            "base64 lengths must match SHA-1 (20B), SHA-256 (32B), SHA-512 (64B)"
        );
    }

    #[test]
    fn oauth1_method_matching_is_case_insensitive() {
        // The signer uppercases before calling, but the builder is public and
        // a wasm caller may not. Both halves must agree on case handling, or
        // a lowercase config value passes the predicate and returns None.
        for method in ["hmac-sha1", "Hmac-Sha256", "HMAC-sha512"] {
            assert!(oauth1_is_supported_signature_method(method), "{method}");
            assert!(
                oauth1_signature("b", "c", "t", method).is_some(),
                "{method}"
            );
        }
    }

    #[test]
    fn oauth1_two_legged_none_token_secret_equals_empty() {
        // RFC 5849 §3.4.2: the signing key is `percent_encode_unreserved(consumer_secret) & percent_encode_unreserved(token_secret)`.
        // In two-legged OAuth there is no token secret, and `None` must be
        // treated as the empty string — not as an absent component, and not
        // as a placeholder. Any other default silently changes every
        // two-legged signature.
        let params = [("a".to_string(), "1".to_string())];
        let build = |token_secret: Option<&str>| {
            oauth1_build_header(&OAuth1BuildParams {
                method: "GET",
                base_uri: "https://example.com/r",
                request_params: &params,
                consumer_key: "ck",
                consumer_secret: "cs",
                token: None,
                token_secret,
                signature_method: "HMAC-SHA1",
                nonce: "n",
                timestamp: "1",
            })
            .expect("HMAC-SHA1 is supported")
            .header
            .value
        };
        assert_eq!(build(None), build(Some("")));
        // NOTE: that the separator is present at all is pinned by the two
        // published vectors (`oauth1_rfc5849_published_vector`,
        // `oauth1_matches_oauth_net_reference_vector`), which both carry a
        // token secret — dropping the `&` fails them. This test covers the
        // half they cannot see: the two-legged case, where `None` must behave
        // exactly like an empty secret rather than taking a different path.
    }

    #[test]
    fn oauth1_header_omits_request_params_but_base_string_signs_them() {
        // §3.5.1: the Authorization header carries only the `oauth_*` params.
        // The base string signs those AND the query/body params. Leaking a
        // request param into the header is a real interop break, and dropping
        // one from the base string is a 401 with no diagnostic.
        let params = [("q".to_string(), "search term".to_string())];
        let out = oauth1_build_header(&OAuth1BuildParams {
            method: "GET",
            base_uri: "https://example.com/r",
            request_params: &params,
            consumer_key: "ck",
            consumer_secret: "cs",
            token: Some("tok"),
            token_secret: Some("ts"),
            signature_method: "HMAC-SHA1",
            nonce: "n",
            timestamp: "1",
        })
        .expect("HMAC-SHA1 is supported");
        assert!(
            !out.header.value.contains("search"),
            "request params must not appear in the header: {}",
            out.header.value
        );
        assert!(
            out.base_string.contains("q%3Dsearch%2520term"),
            "request params must be signed: {}",
            out.base_string
        );
        assert!(out.header.value.starts_with("OAuth "));
        assert!(out.header.value.contains("oauth_token=\"tok\""));
    }
    #[test]
    fn sigv4_default_service_derives_virtual_hosted_endpoints() {
        // Regression (backlog line 60): default_service took the FIRST DNS
        // label, so virtual-hosted endpoints derived the TENANT as the
        // signing service (examplebucket / abc / search-x) — wrong scope,
        // wrong signing key, and for S3 a false is_s3_family → double-encoded
        // path (403 on every virtual-hosted-S3 and API-Gateway request).
        assert_eq!(default_service("s3.us-west-2.amazonaws.com"), "s3");
        assert_eq!(default_service("examplebucket.s3.amazonaws.com"), "s3");
        assert_eq!(
            default_service("examplebucket.s3.us-west-2.amazonaws.com"),
            "s3"
        );
        assert_eq!(
            default_service("mybucket.s3-website-us-west-2.amazonaws.com"),
            "s3"
        );
        assert_eq!(default_service("s3-fips.us-west-2.amazonaws.com"), "s3");
        // Collision-robustness: a tenant that IS a service name must not win
        // over the real (suffix-closest) service label.
        assert_eq!(default_service("es.s3.amazonaws.com"), "s3");
        assert_eq!(
            default_service("abc123.execute-api.us-east-1.amazonaws.com"),
            "execute-api"
        );
        assert_eq!(default_service("search-x.us-east-1.es.amazonaws.com"), "es");
        // Non-virtual-hosted service: first label IS the service.
        assert_eq!(
            default_service("dynamodb.us-east-1.amazonaws.com"),
            "dynamodb"
        );
        // Non-AWS host: first label preserved (unchanged behavior).
        assert_eq!(default_service("api.example.com"), "api");
    }

    #[test]
    fn sigv4_is_fully_derivable_without_the_reqwest_feature() {
        // TR-428: the point of moving the service rules here. This test runs
        // under `--no-default-features`, which is the configuration
        // `tropel-core-wasm` builds — so it fails to COMPILE if any step of
        // the chain drifts back behind the `reqwest` gate.
        //
        // A browser caller starts with a URL and must reach a signed header
        // using nothing but this module. Every step below is a rule that
        // would otherwise have to be re-derived in TypeScript.
        let host = "examplebucket.s3.amazonaws.com";
        let service = default_service(host);
        assert_eq!(service, "s3");
        assert!(is_s3_family(&service));
        let signing_service = signing_name(&service);
        // The input is the path as `Url::path()` yields it — ALREADY
        // single-encoded, so a literal space never arrives here. S3 signs
        // that exactly as sent; every other service encodes it a second
        // time (`%` is not unreserved, so `%20` becomes `%2520`).
        assert_eq!(sigv4_canonical_uri("/a%20b/c", &service), "/a%20b/c");
        assert_eq!(sigv4_canonical_uri("/a%20b/c", "execute-api"), "/a%2520b/c");

        let key = derive_signing_key("SECRET", "20130524", "us-east-1", signing_service);
        let out = aws_sigv4_build_headers(
            &AwsSigV4BuildParams {
                method: "GET",
                path: "/test.txt",
                query: "",
                host,
                headers: &[],
                body: Some(b""),
                access_key: "AKIAIOSFODNN7EXAMPLE",
                secret_key: "SECRET",
                session_token: None,
                region: "us-east-1",
                service: &service,
                amz_date: "20130524T000000Z",
                date_stamp: "20130524",
            },
            &sigv4_canonical_uri("/test.txt", &service),
            signing_service,
            &key,
        );
        assert!(out.headers[0]
            .value
            .starts_with("AWS4-HMAC-SHA256 Credential="));
        assert!(out.headers[0]
            .value
            .contains("/20130524/us-east-1/s3/aws4_request"));
    }

    #[test]
    fn sigv4_signing_name_maps_s3_control() {
        // backlog line 240: s3-control's SIGNING name is "s3" even though the
        // endpoint prefix is not. Getting this wrong changes the credential
        // scope and the signing key, so it is a 403 with no diagnostic.
        assert_eq!(signing_name("s3-control"), "s3");
        assert_eq!(signing_name("s3control"), "s3");
        assert_eq!(signing_name("execute-api"), "execute-api");
    }
}
