//! Pure, data-in/data-out auth header builders.
//!
//! # Why this module exists
//!
//! [`crate::signers`] implements every scheme, and every one of them is behind
//! the `reqwest` feature — because those signers mutate a `reqwest::Request`.
//! `reqwest` cannot compile to `wasm32-unknown-unknown`, so `tropel-core-wasm`
//! turns the feature off, and a browser embedder therefore cannot reach ANY of
//! the signers. KnockPort's digest/hawk/SigV4/OAuth1 configs are creatable and
//! importable today, and every send using them REFUSES.
//!
//! The signing itself was never reqwest-coupled — only the plumbing was. The
//! digest builder read exactly two things off the request (`method` and the
//! request-target), and computed everything else from the challenge. So the
//! fix is to move the computation here, ungated, and leave `signers.rs` as a
//! thin adapter that reads those fields off `reqwest::Request` and calls in.
//!
//! # What this module must never become
//!
//! A second implementation. `signers.rs` calls these functions; it does not
//! keep a parallel copy. That is the whole point — a signing byte-difference
//! is a 403 that takes a day to find, which is why D4 puts signing in Rust in
//! the first place. Two Rust copies would be the same mistake one layer down.
//!
//! The `native_vs_wasm` differential harness already covers OAuth1-HMAC, SigV4
//! and Hawk end to end. Anything moved here inherits that coverage precisely
//! because the signers keep calling it.

use md5::Digest as _;
use sha2::{Sha256, Sha512_256};

// ── Hashes ──────────────────────────────────────────────────────────────────
// Moved here from `signers.rs` rather than duplicated: they are shared by the
// digest builders below and by SigV4's canonical-request hashing, and two
// copies of a hash helper is exactly the drift this module exists to prevent.

/// Hex SHA-256.
pub fn hex_sha256(bytes: &[u8]) -> String {
    hex::encode(Sha256::digest(bytes))
}

/// Hex SHA-512/256.
///
/// A SEPARATE hash with a different IV — **not** the first 256 bits of
/// SHA-512. Truncating SHA-512 produces wrong HA1 values (RFC 7616 §3.9.2);
/// that was a real bug here once.
pub fn hex_sha512_256(bytes: &[u8]) -> String {
    hex::encode(Sha512_256::digest(bytes))
}

/// Hex MD5. Weak, and mandatory: RFC 7616 defaults to it when a server omits
/// `algorithm`, and plenty of servers still do.
pub fn hex_md5(bytes: &[u8]) -> String {
    hex::encode(md5::Md5::digest(bytes))
}

/// Hash with the digest algorithm named by a challenge.
///
/// The `-sess` variants change only how HA1 is DERIVED (nonce and cnonce are
/// folded in); the hash function itself stays the base algorithm, so they map
/// to the same arm here.
pub fn digest_with(input: &str, algorithm: &str) -> String {
    match algorithm {
        "SHA-256" | "SHA-256-SESS" => hex_sha256(input.as_bytes()),
        "SHA-512-256" | "SHA-512-256-SESS" => hex_sha512_256(input.as_bytes()),
        _ => hex_md5(input.as_bytes()),
    }
}

// ── HTTP Digest (RFC 7616) ──────────────────────────────────────────────────

/// One header to attach.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HeaderOut {
    pub name: String,
    pub value: String,
}

/// Everything needed to answer a digest challenge.
///
/// Digest is two-phase and the CALLER drives the 401 → retry, so only the
/// challenge-response half is built here. `nc` is the caller's per-host
/// counter; `cnonce` is generated by the caller (CSPRNG in production, a fixed
/// value in tests so vectors are pinnable).
#[derive(Debug, Clone)]
pub struct DigestBuildParams<'a> {
    pub username: &'a str,
    pub password: &'a str,
    /// Uppercase HTTP method.
    pub method: &'a str,
    /// The request-target: path + query. NOT the full URL — RFC 7616's `uri`
    /// is the origin-form target, and signing the absolute URL is a classic
    /// source of 401 loops against strict servers.
    pub uri: &'a str,
    pub realm: &'a str,
    pub nonce: &'a str,
    pub nc: u64,
    pub cnonce: &'a str,
    /// `qop` from the challenge, if it offered one.
    pub qop: Option<&'a str>,
    /// `algorithm` from the challenge. `None` means the server omitted it, in
    /// which case RFC 7616 says MD5 — and the field is NOT echoed back, since
    /// some strict servers reject an explicit `algorithm=MD5`.
    pub algorithm: Option<&'a str>,
    pub opaque: Option<&'a str>,
}

/// Compute the digest `response` value (HA1/HA2 → response).
pub fn digest_response_value(p: &DigestBuildParams<'_>, algorithm: &str) -> String {
    let base = base_algorithm(algorithm);
    let ha1_plain = digest_with(&format!("{}:{}:{}", p.username, p.realm, p.password), base);
    // RFC 7616 §3.4.4: `-sess` folds the nonce and cnonce into HA1.
    let ha1 = if algorithm.to_ascii_uppercase().ends_with("-SESS") {
        digest_with(&format!("{}:{}:{}", ha1_plain, p.nonce, p.cnonce), base)
    } else {
        ha1_plain
    };
    let ha2 = digest_with(&format!("{}:{}", p.method, p.uri), base);
    match p.qop {
        Some(qop) => digest_with(
            &format!(
                "{}:{}:{:08x}:{}:{}:{}",
                ha1, p.nonce, p.nc, p.cnonce, qop, ha2
            ),
            base,
        ),
        None => digest_with(&format!("{}:{}:{}", ha1, p.nonce, ha2), base),
    }
}

/// The base hash for an algorithm name, with `-sess` stripped.
fn base_algorithm(algorithm: &str) -> &'static str {
    let upper = algorithm.to_ascii_uppercase();
    if upper.starts_with("SHA-512-256") {
        "SHA-512-256"
    } else if upper.starts_with("SHA-256") {
        "SHA-256"
    } else {
        "MD5"
    }
}

/// Does this challenge's `qop` offer `auth`?
///
/// `qop` is a comma-separated LIST (`qop="auth,auth-int"`). Only `auth` is
/// supported; `auth-int` needs the entity body folded into HA2, which the
/// caller does not supply. A challenge offering only `auth-int` therefore
/// falls back to the older no-qop form rather than claiming a qop it did not
/// compute — sending `qop=auth` with an `auth-int` response is an
/// authentication failure that looks like a password problem.
fn qop_offers_auth(qop: Option<&str>) -> bool {
    qop.is_some_and(|q| q.split(',').any(|part| part.trim() == "auth"))
}

/// RFC 7616 §3.4.1 field quoting.
///
/// `qop`, `nc` and `algorithm` are `token` productions and MUST NOT be quoted
/// — strict servers reject `qop="auth"`. Everything else is a `quoted-string`
/// and MUST be.
///
/// The escaping is a SECURITY fix, not cosmetic: a username containing `"`, or
/// one ending in `\`, otherwise breaks out of the quoted string and injects
/// directives — reachable from a CSV data file driving a run. Stripping the
/// quotes instead (the older behaviour) silently corrupted the credential:
/// `ab"c` was signed as `abc`.
fn digest_field(key: &str, value: &str) -> String {
    match key {
        "qop" | "nc" | "algorithm" => format!("{key}={value}"),
        _ => format!(
            "{key}=\"{}\"",
            value.replace('\\', "\\\\").replace('"', "\\\"")
        ),
    }
}

/// Build the `Authorization: Digest …` header for a challenge.
///
/// Covers MD5, SHA-256 and SHA-512-256, each with and without `-sess`. Bruno
/// is MD5-only, so this breadth is the differentiator — which is also why it
/// is worth exporting rather than reimplementing.
///
/// The three cases the shape has to get right, all of them interop failures
/// when wrong:
///   1. `qop` offering `auth` — response uses the nc/cnonce form and the
///      header carries `qop`, `nc` and `cnonce`.
///   2. `qop` present but WITHOUT `auth` — fall back to the no-qop response
///      form and do NOT emit `qop`/`nc`.
///   3. no usable `qop` but a `-sess` algorithm — RFC 7616 §3.4.4 still
///      requires a cnonce (it is folded into HA1), so it is emitted even
///      though `nc` is not.
///
/// Field ORDER matches `signers.rs`'s long-standing output byte for byte, so
/// that delegating to this function is not observable on the wire.
pub fn digest_build_authorization(p: &DigestBuildParams<'_>) -> HeaderOut {
    let algorithm = p
        .algorithm
        .map(|a| a.to_ascii_uppercase())
        .unwrap_or_else(|| "MD5".to_string());
    let is_sess = algorithm.ends_with("-SESS");
    let use_qop = qop_offers_auth(p.qop);

    // The response is computed against the qop the header will actually
    // CLAIM, never against the challenge's raw list.
    let effective = DigestBuildParams {
        qop: if use_qop { Some("auth") } else { None },
        ..p.clone()
    };
    let response = digest_response_value(&effective, &algorithm);

    let mut fields: Vec<(&str, String)> = vec![
        ("username", p.username.to_string()),
        ("realm", p.realm.to_string()),
        ("nonce", p.nonce.to_string()),
        ("uri", p.uri.to_string()),
    ];
    if use_qop {
        fields.push(("qop", "auth".to_string()));
        fields.push(("nc", format!("{:08x}", p.nc)));
        fields.push(("cnonce", p.cnonce.to_string()));
    } else if is_sess {
        // Case 3: no nc, but the cnonce is load-bearing for HA1.
        fields.push(("cnonce", p.cnonce.to_string()));
    }
    fields.push(("response", response));
    // Only echo `algorithm` when the server named one (see DigestBuildParams).
    if p.algorithm.is_some() {
        fields.push(("algorithm", algorithm));
    }
    if let Some(opaque) = p.opaque {
        fields.push(("opaque", opaque.to_string()));
    }

    HeaderOut {
        name: "Authorization".to_string(),
        value: format!(
            "Digest {}",
            fields
                .iter()
                .map(|(k, v)| digest_field(k, v))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

// ── Hawk (hawk.1.header) ────────────────────────────────────────────────────

/// Everything needed to build a Hawk `Authorization` header.
///
/// `ts` and `nonce` are caller-supplied so a vector can be pinned; the signer
/// passes the host clock and a CSPRNG nonce.
#[derive(Debug, Clone)]
pub struct HawkBuildParams<'a> {
    /// HTTP method — uppercased internally.
    pub method: &'a str,
    /// Request-target: path + query.
    pub resource: &'a str,
    /// Host WITHOUT brackets for IPv6; the caller brackets if it must.
    pub host: &'a str,
    pub port: u16,
    pub id: &'a str,
    pub key: &'a str,
    /// `"sha256"` (default) or `"sha1"`.
    pub algorithm: Option<&'a str>,
    /// Unix seconds, as a string.
    pub ts: &'a str,
    pub nonce: &'a str,
    /// Application-specific data folded into the MAC. Empty when unused.
    pub ext: &'a str,
}

/// The Hawk normalized request string.
///
/// Field ORDER is the whole contract: scheme, ts, nonce, method, resource,
/// host, port, hash, ext — each followed by a newline. `ts` and `nonce` come
/// FIRST, immediately after the scheme line. An earlier implementation put
/// method/resource/host/port first and produced a MAC every Hawk server
/// rejects, which is why the order is spelled out rather than inferred.
pub fn hawk_normalized_string(p: &HawkBuildParams<'_>, hash: &str) -> String {
    let method = p.method.to_uppercase();
    let host = p.host.to_lowercase();
    format!(
        "hawk.1.header\n{}\n{}\n{method}\n{}\n{host}\n{}\n{hash}\n{}\n",
        p.ts, p.nonce, p.resource, p.port, p.ext
    )
}

/// Hawk request MAC = base64(HMAC(algorithm, key, normalized)).
///
/// Defaults to SHA-256; `"sha1"` selects the legacy variant. Anything else is
/// treated as SHA-256 rather than refused, matching the signer — a Hawk server
/// that wanted SHA-1 will reject the MAC, which is a loud failure at the wire.
pub fn hawk_mac(normalized: &str, key: &str, algorithm: Option<&str>) -> String {
    use base64::Engine as _;
    use hmac::digest::KeyInit as _;
    use hmac::{Hmac, Mac as _};
    use sha1::Sha1;
    let sha1 = algorithm.is_some_and(|a| a.eq_ignore_ascii_case("sha1"));
    if sha1 {
        let mut mac =
            Hmac::<Sha1>::new_from_slice(key.as_bytes()).expect("HMAC-SHA1 accepts any key length");
        mac.update(normalized.as_bytes());
        base64::engine::general_purpose::STANDARD.encode(mac.finalize().into_bytes())
    } else {
        let mut mac = Hmac::<Sha256>::new_from_slice(key.as_bytes())
            .expect("HMAC-SHA256 accepts any key length");
        mac.update(normalized.as_bytes());
        base64::engine::general_purpose::STANDARD.encode(mac.finalize().into_bytes())
    }
}

/// Build the `Authorization: Hawk …` header.
///
/// Payload validation (`hash`) is deliberately not implemented — the signer
/// has never sent one, and emitting an empty `hash=""` would be worse than
/// omitting it. The normalized string still carries the empty hash field,
/// because the spec's field COUNT is fixed.
pub fn hawk_build_header(p: &HawkBuildParams<'_>) -> HeaderOut {
    let normalized = hawk_normalized_string(p, "");
    let mac = hawk_mac(&normalized, p.key, p.algorithm);
    HeaderOut {
        name: "Authorization".to_string(),
        value: format!(
            "Hawk id=\"{}\", ts=\"{}\", nonce=\"{}\", mac=\"{}\"",
            p.id, p.ts, p.nonce, mac
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn params<'a>(algorithm: Option<&'a str>, qop: Option<&'a str>) -> DigestBuildParams<'a> {
        DigestBuildParams {
            username: "Mufasa",
            password: "Circle Of Life",
            method: "GET",
            uri: "/dir/index.html",
            realm: "testrealm@host.com",
            nonce: "dcd98b7102dd2f0e8b11d0f600bfb0c093",
            nc: 1,
            cnonce: "0a4f113b",
            qop,
            algorithm,
            opaque: Some("5ccc069c403ebaf9f0171e9517f40e41"),
        }
    }

    #[test]
    fn rfc_2617_md5_qop_auth_vector() {
        // The canonical RFC 2617 §3.5 example. A published vector is the point:
        // it cannot drift with the implementation the way a self-generated
        // expectation can.
        let out = digest_response_value(&params(Some("MD5"), Some("auth")), "MD5");
        assert_eq!(out, "6629fae49393a05397450978507c4ef1");
    }

    #[test]
    fn sess_changes_the_response_and_the_base_hash_does_not() {
        // `-sess` folds nonce+cnonce into HA1, so the response MUST differ …
        let plain = digest_response_value(&params(Some("MD5"), Some("auth")), "MD5");
        let sess = digest_response_value(&params(Some("MD5-sess"), Some("auth")), "MD5-SESS");
        assert_ne!(plain, sess);
        // … while the hash function itself stays MD5 (32 hex chars).
        assert_eq!(sess.len(), 32);
    }

    #[test]
    fn sha256_and_sha512_256_are_distinct_and_correctly_sized() {
        let s256 = digest_response_value(&params(Some("SHA-256"), Some("auth")), "SHA-256");
        let s512 = digest_response_value(&params(Some("SHA-512-256"), Some("auth")), "SHA-512-256");
        assert_eq!(s256.len(), 64);
        assert_eq!(s512.len(), 64);
        // SHA-512/256 is a separate hash, not truncated SHA-512 — if it were
        // implemented as a truncation these would still differ, but the
        // published-vector test above is what pins the actual bytes.
        assert_ne!(s256, s512);
    }

    #[test]
    fn algorithm_is_echoed_only_when_the_server_named_one() {
        // Some strict servers reject an explicit `algorithm=MD5`.
        let named = digest_build_authorization(&params(Some("MD5"), Some("auth")));
        assert!(named.value.contains("algorithm=MD5"));
        let omitted = digest_build_authorization(&params(None, Some("auth")));
        assert!(!omitted.value.contains("algorithm="), "{}", omitted.value);
        // …and it still hashes as MD5, which is RFC 7616's default.
        assert!(omitted.value.contains("response=\""));
    }

    #[test]
    fn qop_controls_nc_and_cnonce() {
        // Without qop the response formula is the older 3-part form and the
        // header must NOT carry nc/cnonce — sending them anyway is a common
        // interop failure.
        let with = digest_build_authorization(&params(Some("MD5"), Some("auth")));
        assert!(with.value.contains("nc=00000001") && with.value.contains("cnonce="));
        let without = digest_build_authorization(&params(Some("MD5"), None));
        assert!(!without.value.contains("nc="), "{}", without.value);
        assert!(!without.value.contains("cnonce="), "{}", without.value);
    }

    #[test]
    fn qop_is_a_list_and_only_auth_counts() {
        // `qop="auth,auth-int"` must be honoured as auth …
        let mut p = params(Some("MD5"), Some("auth,auth-int"));
        let out = digest_build_authorization(&p);
        assert!(out.value.contains("qop=auth"), "{}", out.value);
        assert!(out.value.contains("nc=00000001"));

        // … and the header must claim plain `auth`, never echo the raw list.
        assert!(!out.value.contains("auth-int"), "{}", out.value);

        // A challenge offering ONLY auth-int falls back to the no-qop form:
        // auth-int folds the entity body into HA2, which we do not compute, so
        // claiming it would be an auth failure that looks like a bad password.
        p.qop = Some("auth-int");
        let fallback = digest_build_authorization(&p);
        assert!(!fallback.value.contains("qop="), "{}", fallback.value);
        assert!(!fallback.value.contains("nc="), "{}", fallback.value);
    }

    #[test]
    fn sess_without_qop_still_carries_a_cnonce() {
        // RFC 7616 §3.4.4: `-sess` folds the cnonce into HA1, so it is
        // load-bearing even when there is no qop — and `nc` still is not.
        let out = digest_build_authorization(&params(Some("MD5-sess"), None));
        assert!(out.value.contains("cnonce=\"0a4f113b\""), "{}", out.value);
        assert!(!out.value.contains("nc="), "{}", out.value);

        // Non-sess without qop carries neither.
        let plain = digest_build_authorization(&params(Some("MD5"), None));
        assert!(!plain.value.contains("cnonce="), "{}", plain.value);
    }

    #[test]
    fn the_response_is_computed_against_the_qop_the_header_claims() {
        // The subtle one. With `auth-int` only, the header drops qop — so the
        // RESPONSE must use the no-qop formula too. Computing the nc/cnonce
        // form while advertising no qop is a silent mismatch the server
        // rejects as a bad password.
        let auth_int = digest_build_authorization(&params(Some("MD5"), Some("auth-int")));
        let no_qop = digest_build_authorization(&params(Some("MD5"), None));
        let resp = |h: &HeaderOut| {
            h.value
                .split("response=\"")
                .nth(1)
                .and_then(|r| r.split('"').next())
                .unwrap()
                .to_string()
        };
        assert_eq!(resp(&auth_int), resp(&no_qop));
    }

    #[test]
    fn rfc_7616_published_vectors_md5_and_sha256() {
        // Moved here from `signers.rs` with the delegation (TR-424): the
        // computation lives here now, so its published vectors do too.
        //
        // NOTE: RFC 7616 spells the password "Circle of Life" (lowercase o)
        // while RFC 2617 uses "Circle Of Life". The two RFCs genuinely
        // differ — keep each test faithful to its own source.
        let vector = |algorithm: &'static str| DigestBuildParams {
            username: "Mufasa",
            password: "Circle of Life",
            method: "GET",
            uri: "/dir/index.html",
            realm: "http-auth@example.org",
            nonce: "7ypf/xlj9XXwfDPEoM4URrv/xwf94BcCAzFZH4GiTo0v",
            nc: 1,
            cnonce: "f2/wE4q74E6zIJEtWaHKaf5wv/H5QzzpXusqGemxURZJ",
            qop: Some("auth"),
            algorithm: Some(algorithm),
            opaque: None,
        };

        assert_eq!(
            digest_response_value(&vector("MD5"), "MD5"),
            "8ca523f5e9506fed4657c9700eebdbec",
            "RFC 7616 §3.9.1 published MD5 response"
        );
        assert_eq!(
            digest_response_value(&vector("SHA-256"), "SHA-256"),
            "753927fa0e85d155564e2e272a28d1802ca10daf4496794697cf8db5856cb6c1",
            "RFC 7616 §3.9.1 published SHA-256 response"
        );
    }

    #[test]
    fn ha1_and_ha2_match_the_published_intermediates() {
        // The RFC publishes the intermediates too. Asserting them separately
        // means a failure says WHICH half is wrong, instead of only that the
        // final response differs.
        assert_eq!(
            digest_with("Mufasa:testrealm@host.com:Circle Of Life", "MD5"),
            "939e7578ed9e3c518a452acee763bce9",
            "RFC 2617 §3.5 HA1"
        );
        assert_eq!(
            digest_with("GET:/dir/index.html", "MD5"),
            "39aff3a2bab6126f332b942af96d3366",
            "RFC 2617 §3.5 HA2"
        );
    }

    #[test]
    fn quoted_string_values_are_escaped_not_stripped() {
        // SECURITY, not cosmetics. A username ending in a backslash otherwise
        // terminates the quoted-string early and the rest of the header is
        // read as directives — reachable from a CSV data file driving a run.
        // Stripping the quotes instead (the behaviour before P2 line 180)
        // silently signed a DIFFERENT credential: `ab"c` became `abc`.
        let mut p = params(Some("MD5"), Some("auth"));
        p.username = r#"ab"c"#;
        let out = digest_build_authorization(&p);
        assert!(
            out.value.contains(r#"username="ab\"c""#),
            "quote must be escaped, not stripped: {}",
            out.value
        );

        p.username = r"trailing\";
        let out = digest_build_authorization(&p);
        assert!(
            out.value.contains(r#"username="trailing\\""#),
            "backslash must be escaped so it cannot break out: {}",
            out.value
        );
    }

    #[test]
    fn token_fields_are_unquoted_and_the_rest_are_quoted() {
        // RFC 7616 §3.4.1: qop/nc/algorithm are `token`, and strict servers
        // reject `qop="auth"`. Everything else is `quoted-string`.
        let out = digest_build_authorization(&params(Some("MD5"), Some("auth"))).value;
        assert!(out.contains("qop=auth,"), "{out}");
        assert!(out.contains("nc=00000001,"), "{out}");
        assert!(out.contains("algorithm=MD5"), "{out}");
        assert!(out.contains(r#"realm="testrealm@host.com""#), "{out}");
        assert!(out.contains(r#"cnonce="0a4f113b""#), "{out}");
    }

    #[test]
    fn field_order_is_the_wire_order() {
        // Pinned because `signers.rs` delegates here: a reordering would be
        // observable on the wire even though every field is still present.
        let out = digest_build_authorization(&params(Some("MD5"), Some("auth"))).value;
        let order: Vec<&str> = [
            "username",
            "realm",
            "nonce",
            "uri",
            "qop",
            "nc",
            "cnonce",
            "response",
            "algorithm",
            "opaque",
        ]
        .into_iter()
        .filter(|k| out.contains(&format!("{k}=")))
        .collect();
        let positions: Vec<usize> = order
            .iter()
            .map(|k| out.find(&format!("{k}=")).unwrap())
            .collect();
        let mut sorted = positions.clone();
        sorted.sort_unstable();
        assert_eq!(positions, sorted, "fields out of wire order: {out}");
    }

    // ── Hawk ─────────────────────────────────────────────────────────────

    fn hawk<'a>(algorithm: Option<&'a str>) -> HawkBuildParams<'a> {
        HawkBuildParams {
            method: "GET",
            resource: "/resource/1?b=1&a=2",
            host: "example.com",
            port: 8000,
            id: "dh37fgj492je",
            key: "werxhqb98rpaxn39848xrunpaw3489ruxnpa98w4rxn",
            algorithm,
            ts: "1353832234",
            nonce: "j4h3g2",
            ext: "some-app-ext-data",
        }
    }

    #[test]
    fn hawk_normalized_string_matches_the_spec_vector() {
        // The published example from the Hawk spec / mozilla-hawk's own
        // README. Field ORDER is the whole contract here: ts and nonce come
        // FIRST, right after the scheme line. An earlier implementation put
        // method/resource/host/port first and produced a MAC every Hawk
        // server rejects — a bug a length check would never have caught.
        let out = hawk_normalized_string(&hawk(None), "");
        assert_eq!(
            out,
            "hawk.1.header\n1353832234\nj4h3g2\nGET\n/resource/1?b=1&a=2\nexample.com\n8000\n\nsome-app-ext-data\n"
        );
    }

    #[test]
    fn hawk_mac_matches_the_published_vector() {
        // Hawk spec §3.2.1 example → the published MAC for the string above.
        let normalized = hawk_normalized_string(&hawk(None), "");
        assert_eq!(
            hawk_mac(&normalized, hawk(None).key, None),
            "6R4rV5iE+NPoym+WwjeHzjAGXUtLNIxmo1vpMofpLAE="
        );
    }

    #[test]
    fn hawk_payload_hash_vector() {
        // Hawk API.md "Payload Validation": the same request WITH a payload
        // hash. Ported from `signers.rs` with the delegation (TR-425) — a
        // distinct published vector from the empty-hash one above, and the
        // only thing that pins the `hash` field's position in the normalized
        // string. `hawk_build_header` never sends one, but the normalizer
        // must still place it correctly for anything that does.
        let mut p = hawk(None);
        p.method = "POST";
        let normalized = hawk_normalized_string(&p, "Yi9LfIIFRtBEPt74PVmbTF/xVAwPn7ub15ePICfgnuY=");
        assert_eq!(
            hawk_mac(&normalized, p.key, None),
            "aSe1DERmZuRl3pI36/9BdZmnErTw3sNzOOAUlfeKjVw="
        );
    }

    #[test]
    fn hawk_method_uppercases_and_host_lowercases() {
        // Both are normalization the spec requires; getting either wrong
        // changes the MAC without changing anything visible in the header.
        let mut p = hawk(None);
        p.method = "get";
        p.host = "EXAMPLE.com";
        assert_eq!(
            hawk_normalized_string(&p, ""),
            hawk_normalized_string(&hawk(None), "")
        );
    }

    #[test]
    fn hawk_sha1_differs_from_sha256_and_unknown_falls_back() {
        let n = hawk_normalized_string(&hawk(None), "");
        let k = hawk(None).key;
        let sha256 = hawk_mac(&n, k, None);
        let sha1 = hawk_mac(&n, k, Some("sha1"));
        assert_ne!(sha256, sha1);
        // Case-insensitive, and an unrecognised algorithm falls back to
        // SHA-256 rather than refusing — the server rejects the MAC, which is
        // a loud failure at the wire rather than a silent local one.
        assert_eq!(hawk_mac(&n, k, Some("SHA1")), sha1);
        assert_eq!(hawk_mac(&n, k, Some("md5")), sha256);
    }

    #[test]
    fn hawk_header_carries_id_ts_nonce_and_mac() {
        let out = hawk_build_header(&hawk(None));
        assert!(
            out.value.starts_with("Hawk id=\"dh37fgj492je\""),
            "{}",
            out.value
        );
        assert!(out.value.contains("ts=\"1353832234\""), "{}", out.value);
        assert!(out.value.contains("nonce=\"j4h3g2\""), "{}", out.value);
        assert!(out.value.contains("mac=\""), "{}", out.value);
        // No payload hash is sent, so none is advertised — an empty
        // `hash=""` would be worse than omitting it.
        assert!(!out.value.contains("hash="), "{}", out.value);
    }

    #[test]
    fn nc_is_eight_hex_digits() {
        let mut p = params(Some("MD5"), Some("auth"));
        p.nc = 255;
        assert!(digest_build_authorization(&p).value.contains("nc=000000ff"));
    }
}
