[package]
name = "tropel-x-prometheus"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
tropel-sdk = { workspace = true, features = ["unstable-output"] }
tropel-report.workspace = true
async-trait.workspace = true
inventory.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true
