//! `tropel-core-wasm` — the eager-loaded core tier for browser embedders
//! (KnockPort). wasm32-unknown-unknown + wasm-bindgen; deliberately NO
//! QuickJS: see `API_CLIENT_WEB_PAYLOAD.md` §2.3 (two-tier wasm). The
//! website/web app only ever talks to HTTP through a relay (CORS), so the
//! heavy `tropel-web` (wasip1 + QuickJS) scenario slice is extension/native
//! territory; this crate covers the pure compute the page always needs —
//! starting with the dynamic-variable catalog.
//!
//! Exports are thin adapters over `tropel-variables` — the catalog itself is
//! NOT duplicated here, so the website, the extension and the native runner
//! cannot drift.

use std::sync::OnceLock;

use tropel_auth::oauth::{
    attach_token, build_authorize_url, build_token_request, decode_jwt, jwt_expires_at,
    parse_token_response, sign_jwt, sign_wsse, AuthorizeParams, JwtAlgorithm, StoredToken,
    TokenPlacement, TokenRequestParams, WsseParams,
};
use tropel_variables::{DynamicCatalog, PREDEFINED_VARIABLE_META};
use wasm_bindgen::prelude::*;

static CATALOG: OnceLock<DynamicCatalog> = OnceLock::new();

fn catalog() -> &'static DynamicCatalog {
    CATALOG.get_or_init(DynamicCatalog::new)
}

/// Resolve every predefined dynamic variable (`{{$guid}}`, `{{$timestamp}}`,
/// …) in the input. Each occurrence generates a fresh value; unknown `{{$…}}`
/// names survive as literal placeholders (Tropel semantics). Plain `{{var}}`
/// references are untouched — the embedder resolves those against its own
/// environment/collection maps.
///
/// TR-403: returns `Result` — a total-output cap (16 MiB) produces a JS
/// `Error` with the message naming the limit, so the consumer never receives
/// silently truncated data on the wire.
#[wasm_bindgen(js_name = "resolveVariables")]
pub fn resolve_variables(input: &str) -> Result<String, wasm_bindgen::JsValue> {
    catalog()
        .resolve(input)
        .map_err(|msg| wasm_bindgen::JsValue::from_str(&msg))
}

/// Catalog metadata as a JSON string: `[{"name":"$guid","description":…},…]`.
/// Feed the names into editor autocomplete; the descriptions into tooltips.
#[wasm_bindgen(js_name = "predefinedVariablesMeta")]
pub fn predefined_variables_meta() -> String {
    let entries = PREDEFINED_VARIABLE_META.iter().map(|m| {
        format!(
            "{{\"name\":\"{}\",\"description\":\"{}\"}}",
            m.name, m.description
        )
    });
    format!("[{}]", entries.collect::<Vec<_>>().join(","))
}

// ── OAuth2 flows (tropel-auth::oauth, pure — the embedder sends the requests) ─────

fn err(e: impl std::fmt::Display) -> JsValue {
    // ASCII-only: the web-target glue truncates strings at their UTF-16 code
    // unit count when encoding into wasm memory, so any multi-byte UTF-8
    // character would corrupt the message at the JS boundary.
    JsValue::from_str(
        &e.to_string()
            .chars()
            .map(|c| if c.is_ascii() { c } else { '?' })
            .collect::<String>(),
    )
}

fn parse_json<T: serde::de::DeserializeOwned>(s: &str) -> Result<T, JsValue> {
    serde_json::from_str(s).map_err(err)
}

fn to_json<T: serde::Serialize>(v: &T) -> Result<String, JsValue> {
    serde_json::to_string(v).map_err(err)
}

/// Compute the S256 PKCE challenge for a host-side verifier → JSON
/// `{code_verifier, code_challenge_method:"S256", code_challenge}`. The
/// verifier is generated by the embedder (`crypto.getRandomValues`, 43–128
/// chars of the RFC 7636 charset); the challenge is computed here so it
/// matches the token-request builder byte for byte. Validates length.
#[wasm_bindgen(js_name = "oauth2GeneratePkcePair")]
pub fn oauth2_generate_pkce_pair(verifier: &str) -> Result<String, JsValue> {
    if verifier.len() < 43 || verifier.len() > 128 {
        return Err(err("code_verifier must be 43-128 characters (RFC 7636)"));
    }
    let pair = tropel_auth::oauth::PkcePair {
        code_verifier: verifier.to_string(),
        code_challenge_method: "S256".to_string(),
        code_challenge: tropel_auth::oauth::code_challenge_s256(verifier),
    };
    to_json(&pair)
}

/// Build the OAuth2 authorize URL (authorization_code / implicit) from JSON
/// `AuthorizeParams` `{auth_url, client_id, redirect_uri, scopes[],
/// response_type?, state?, pkce?{code_verifier,code_challenge_method},
/// extra?[[k,v]]}` → JSON `{url, state, code_verifier?}`. Throws on invalid
/// input.
#[wasm_bindgen(js_name = "oauth2BuildAuthorizeUrl")]
pub fn oauth2_build_authorize_url(params_json: &str) -> Result<String, JsValue> {
    let params: AuthorizeParams = parse_json(params_json)?;
    let req = build_authorize_url(&params).map_err(err)?;
    to_json(&req)
}

/// Build the OAuth2 token-endpoint POST from JSON `TokenRequestParams`
/// `{grant_type: "authorization_code"|"client_credentials"|"password"|
/// "refresh_token", token_url, client_id, client_secret?, auth_method?:
/// "basic"|"post_body", code?, redirect_uri?, code_verifier?, username?,
/// password?, refresh_token?, scopes[]}` → JSON `{url, body,
/// basic_auth_header?, content_type}`.
#[wasm_bindgen(js_name = "oauth2BuildTokenRequest")]
pub fn oauth2_build_token_request(params_json: &str) -> Result<String, JsValue> {
    let params: TokenRequestParams = parse_json(params_json)?;
    let req = build_token_request(&params).map_err(err)?;
    to_json(&req)
}

/// Parse a token-endpoint response body → JSON `{access_token, token_type?,
/// expires_in?, refresh_token?, scope?, id_token?}`. Throws on `error`
/// payloads (RFC 6749 §5.2) and malformed JSON.
#[wasm_bindgen(js_name = "oauth2ParseTokenResponse")]
pub fn oauth2_parse_token_response(body: &str) -> Result<String, JsValue> {
    let tr = parse_token_response(body).map_err(err)?;
    to_json(&tr)
}

/// Fold a parsed token response into a stored token with an absolute
/// `expires_at` (host clock at call time). Input: parsed-response JSON.
/// Output: JSON `{access_token, token_type, refresh_token?, expires_at?,
/// scope?}`.
#[wasm_bindgen(js_name = "oauth2StoreToken")]
pub fn oauth2_store_token(parsed_json: &str) -> Result<String, JsValue> {
    let tr: tropel_auth::oauth::TokenResponse = parse_json(parsed_json)?;
    to_json(&StoredToken::from_response(&tr))
}

/// Is a stored token expired? Input: stored-token JSON + skew seconds
/// (e.g. 60). Tokens without `expires_at` are never expired.
#[wasm_bindgen(js_name = "oauth2IsTokenExpired")]
pub fn oauth2_is_token_expired(token_json: &str, skew_secs: i64) -> Result<bool, JsValue> {
    let token: StoredToken = parse_json(token_json)?;
    Ok(token.is_expired(skew_secs))
}

/// Position a token on a request → JSON `{kind:"header"|"query", key, value}`
/// from JSON `TokenAttachment`. `placement` is `"header"` or `"query"`;
/// `header_prefix`/`query_key` may be empty strings for defaults
/// (`Bearer` / `access_token`).
#[wasm_bindgen(js_name = "oauth2AttachToken")]
pub fn oauth2_attach_token(
    token: &str,
    token_type: &str,
    placement: &str,
    header_prefix: &str,
    query_key: &str,
) -> Result<String, JsValue> {
    let placement = match placement {
        "header" => TokenPlacement::Header,
        "query" => TokenPlacement::Query,
        other => return Err(err(format!("unknown placement: {other}"))),
    };
    let att = attach_token(
        token,
        if token_type.is_empty() {
            None
        } else {
            Some(token_type)
        },
        placement,
        if header_prefix.is_empty() {
            None
        } else {
            Some(header_prefix)
        },
        if query_key.is_empty() {
            None
        } else {
            Some(query_key)
        },
    );
    to_json(&att)
}

/// Decode a compact JWT (no signature verification — clients display tokens,
/// they don't trust them) → JSON `{header, payload, signature}`.
#[wasm_bindgen(js_name = "oauth2DecodeJwt")]
pub fn oauth2_decode_jwt(token: &str) -> Result<String, JsValue> {
    let jwt = decode_jwt(token).map_err(err)?;
    to_json(&jwt)
}

/// The JWT `exp` claim (UNIX seconds) or `-1` when absent. Throws on a
/// malformed token.
#[wasm_bindgen(js_name = "oauth2JwtExpiresAt")]
pub fn oauth2_jwt_expires_at(token: &str) -> Result<i64, JsValue> {
    Ok(jwt_expires_at(token).map_err(err)?.unwrap_or(-1))
}

/// Sign a compact JWT with an HMAC-SHA2 algorithm and return the compact
/// `header.payload.signature` string. `header_json` may be `""` (defaults to
/// `{"alg","typ":"JWT"}`) — when present it must be a JSON object; `alg` is
/// always replaced with the algorithm actually used, `typ` filled in when
/// missing. `payload_json` must be a JSON object. `algorithm` is `HS256`,
/// `HS384` or `HS512`.
#[wasm_bindgen(js_name = "oauth2SignJwt")]
pub fn oauth2_sign_jwt(
    header_json: &str,
    payload_json: &str,
    algorithm: &str,
    secret: &str,
) -> Result<String, JsValue> {
    let header: Option<serde_json::Value> = if header_json.is_empty() {
        None
    } else {
        Some(parse_json(header_json)?)
    };
    let payload: serde_json::Value = parse_json(payload_json)?;
    let algorithm = match algorithm {
        "HS256" => JwtAlgorithm::Hs256,
        "HS384" => JwtAlgorithm::Hs384,
        "HS512" => JwtAlgorithm::Hs512,
        other => return Err(err(format!("unknown algorithm: {other}"))),
    };
    sign_jwt(header.as_ref(), &payload, algorithm, secret).map_err(err)
}

// ── WSSE UsernameToken (SOAP, SHA-1 digest profile) ──────────────────────────

/// Build a WSSE UsernameToken security header set → JSON
/// `{authorization, nonce, created}` from JSON `WsseParams`
/// `{username, password, nonce?, created?}`. Empty nonce/created are
/// generated (base64 random nonce + host-clock RFC 3339 timestamp); the
/// embedder attaches `authorization` as the `Authorization` header.
#[wasm_bindgen(js_name = "wsseSign")]
pub fn wsse_sign(params_json: &str) -> Result<String, JsValue> {
    let params: WsseParams = parse_json(params_json)?;
    to_json(&sign_wsse(&params).map_err(err)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_guid() {
        let out = resolve_variables("id={{$guid}}").unwrap();
        assert!(out.starts_with("id="));
        let guid = out.strip_prefix("id=").unwrap();
        assert_eq!(guid.len(), 36);
        assert!(!out.contains("{{$guid}}"));
    }

    #[test]
    fn plain_vars_survive() {
        let out = resolve_variables("{{baseUrl}}/x").unwrap();
        assert_eq!(out, "{{baseUrl}}/x");
    }

    #[test]
    fn meta_is_well_formed_json() {
        let json = predefined_variables_meta();
        let parsed: Vec<serde_json::Value> = serde_json::from_str(&json).expect("valid JSON");
        assert!(parsed.len() >= 30, "metadata covers the catalog");
        assert_eq!(parsed[0]["name"], "$guid");
        for entry in &parsed {
            assert!(entry["name"].as_str().unwrap().starts_with('$'));
            assert!(!entry["description"].as_str().unwrap().is_empty());
        }
    }

    #[test]
    fn meta_names_all_resolve() {
        let json = predefined_variables_meta();
        let parsed: Vec<serde_json::Value> = serde_json::from_str(&json).unwrap();
        for entry in parsed {
            let name = entry["name"].as_str().unwrap();
            // Parameterized entries carry an argument in their description
            // example (`{{$randomString:16}}`); resolve the bare form.
            let resolved = catalog().resolve(&format!("{{{{{name}}}}}")).unwrap();
            assert!(
                !resolved.contains(&format!("{{{{{name}}}}}")),
                "{name} must resolve"
            );
        }
    }

    // The oauth adapter layer is exercised end-to-end against the REAL wasm
    // by packages/core-wasm/smoke.mjs — JsValue cannot be constructed in
    // native test builds, so it is covered here only via tropel-oauth's own
    // unit tests (the adapters are serde pass-throughs).
}
