[package]
name = "tropel-native"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tropel-core.workspace = true
tropel-js.workspace = true
rquickjs.workspace = true
sha2.workspace = true
sha1.workspace = true
sha3.workspace = true
md-5.workspace = true
md4.workspace = true
ripemd.workspace = true
hmac.workspace = true
hmac012.workspace = true
aes.workspace = true
aes-gcm.workspace = true
cbc.workspace = true
base64.workspace = true
hex.workspace = true
percent-encoding.workspace = true
uuid.workspace = true
rand.workspace = true
regex.workspace = true
serde_json.workspace = true
simd-json.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
