[package]
name = "tropel-http"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
tropel-sdk.workspace = true
tropel-auth.workspace = true
tropel-core.workspace = true
reqwest.workspace = true
tower.workspace = true
serde_json.workspace = true
simd-json.workspace = true
tracing.workspace = true
tokio.workspace = true
serde_urlencoded.workspace = true
