[package]
name = "tropel-http"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
tropel-sdk.workspace = true
tropel-core.workspace = true
tropel-metrics.workspace = true
reqwest.workspace = true
tower.workspace = true
serde.workspace = true
serde_json.workspace = true
simd-json.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true
chrono.workspace = true
anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true
base64.workspace = true
sha2.workspace = true
sha1.workspace = true
md-5.workspace = true
hmac.workspace = true
hex.workspace = true
percent-encoding.workspace = true
serde_urlencoded.workspace = true
indexmap.workspace = true
rand.workspace = true
